//! This file was generated by [Specta](https://github.com/specta-rs/specta)
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Deserialize, Serialize)]
pub enum GetTokenTokenServiceType { 
    #[serde(rename = "com.apple.maid")]
	ComAppleMaid,
    #[serde(rename = "com.apple.watch.pairing")]
	ComAppleWatchPairing,
}

#[derive(Debug, Clone, Deserialize, Serialize)]
#[derive(bira::Builder)]

pub struct GetTokenTokenParameter {
    #[serde(rename = "SecurityToken")]
    #[serde(default, skip_serializing_if = "Option::is_none", deserialize_with = "deserialize_some", serialize_with = "serialize_some",)]
    pub security_token: Option<String>,
    #[serde(rename = "PhoneUDID")]
    #[serde(default, skip_serializing_if = "Option::is_none", deserialize_with = "deserialize_some", serialize_with = "serialize_some",)]
    pub phone_udid: Option<String>,
    #[serde(rename = "WatchUDID")]
    #[serde(default, skip_serializing_if = "Option::is_none", deserialize_with = "deserialize_some", serialize_with = "serialize_some",)]
    pub watch_udid: Option<String>,
}

/// Check-in protocol get token data.
#[derive(Debug, Clone, Deserialize, Serialize)]
#[derive(bira::Builder)]

pub struct GetToken {
    /// A string that specifies the service for the requested token.
    #[serde(rename = "TokenServiceType")]
    pub token_service_type: GetTokenTokenServiceType,
    /// Parameters that the system uses to generate the token.
    #[serde(rename = "TokenParameters")]
    #[serde(default, skip_serializing_if = "Option::is_none", deserialize_with = "deserialize_some", serialize_with = "serialize_some",)]
    pub token_parameters: Option<GetTokenTokenParameter>,
    /// The device's UDID.
    #[serde(rename = "UDID")]
    #[serde(default, skip_serializing_if = "Option::is_none", deserialize_with = "deserialize_some", serialize_with = "serialize_some",)]
    pub udid: Option<String>,
    /// A per-enrollment identifier that identifies the device for user enrollments.
    #[serde(rename = "EnrollmentID")]
    #[serde(default, skip_serializing_if = "Option::is_none", deserialize_with = "deserialize_some", serialize_with = "serialize_some",)]
    pub enrollment_id: Option<String>,
    /// A per-enrollment identifier that identifies the user for user enrollments.
    #[serde(rename = "EnrollmentUserID")]
    #[serde(default, skip_serializing_if = "Option::is_none", deserialize_with = "deserialize_some", serialize_with = "serialize_some",)]
    pub enrollment_user_id: Option<String>,
    /// On Shared iPad, this value returns the Managed Apple Account identifier of the user. When present, it indicates that the token is for the user channel. In macOS, this value returns the short name of the user.
    #[serde(rename = "UserShortName")]
    #[serde(default, skip_serializing_if = "Option::is_none", deserialize_with = "deserialize_some", serialize_with = "serialize_some",)]
    pub user_short_name: Option<String>,
    /// In macOS, this value returns the ID of the user. On Shared iPad, this value is 'FFFFFFFF-FFFF-FFFF-FFFF-FFFFFFFFFFFF' to indicate that no authentication occurs.
    #[serde(rename = "UserID")]
    #[serde(default, skip_serializing_if = "Option::is_none", deserialize_with = "deserialize_some", serialize_with = "serialize_some",)]
    pub user_id: Option<String>,
    /// The full name of the user.
    #[serde(rename = "UserLongName")]
    #[serde(default, skip_serializing_if = "Option::is_none", deserialize_with = "deserialize_some", serialize_with = "serialize_some",)]
    pub user_long_name: Option<String>,
}

/// Check-in protocol authenticate request keys.
#[derive(Debug, Clone, Deserialize, Serialize)]
#[derive(bira::Builder)]

pub struct Authenticate {
    /// The device's name.
    #[serde(rename = "DeviceName")]
    #[serde(default, skip_serializing_if = "Option::is_none", deserialize_with = "deserialize_some", serialize_with = "serialize_some",)]
    pub device_name: Option<String>,
    /// The device's model name.
    #[serde(rename = "ModelName")]
    #[serde(default, skip_serializing_if = "Option::is_none", deserialize_with = "deserialize_some", serialize_with = "serialize_some",)]
    pub model_name: Option<String>,
    /// The device's model.
    #[serde(rename = "Model")]
    #[serde(default, skip_serializing_if = "Option::is_none", deserialize_with = "deserialize_some", serialize_with = "serialize_some",)]
    pub model: Option<String>,
    /// The topic to which the device subscribes.
    #[serde(rename = "Topic")]
    pub topic: String,
    /// The device's UDID (Unique Device ID). The system requires this value if the enrollment type isn't user enrollment.
    #[serde(rename = "UDID")]
    #[serde(default, skip_serializing_if = "Option::is_none", deserialize_with = "deserialize_some", serialize_with = "serialize_some",)]
    pub udid: Option<String>,
    /// The per-enrollment identifier for the device. The system requires this value if the enrollment type is user enrollment.
    /// Available in macOS 10.15 and iOS 13.0 and later.
    #[serde(rename = "EnrollmentID")]
    #[serde(default, skip_serializing_if = "Option::is_none", deserialize_with = "deserialize_some", serialize_with = "serialize_some",)]
    pub enrollment_id: Option<String>,
    /// The device's OS version.
    #[serde(rename = "OSVersion")]
    #[serde(default, skip_serializing_if = "Option::is_none", deserialize_with = "deserialize_some", serialize_with = "serialize_some",)]
    pub os_version: Option<String>,
    /// The device's build version.
    #[serde(rename = "BuildVersion")]
    #[serde(default, skip_serializing_if = "Option::is_none", deserialize_with = "deserialize_some", serialize_with = "serialize_some",)]
    pub build_version: Option<String>,
    /// The device's product name ('iPhone3,1').
    #[serde(rename = "ProductName")]
    #[serde(default, skip_serializing_if = "Option::is_none", deserialize_with = "deserialize_some", serialize_with = "serialize_some",)]
    pub product_name: Option<String>,
    /// The device's serial number.
    #[serde(rename = "SerialNumber")]
    #[serde(default, skip_serializing_if = "Option::is_none", deserialize_with = "deserialize_some", serialize_with = "serialize_some",)]
    pub serial_number: Option<String>,
    /// The device's IMEI (International Mobile Station Equipment Identity).
    #[serde(rename = "IMEI")]
    #[serde(default, skip_serializing_if = "Option::is_none", deserialize_with = "deserialize_some", serialize_with = "serialize_some",)]
    pub imei: Option<String>,
    /// The device's MEID (Mobile Equipment Identifier).
    #[serde(rename = "MEID")]
    #[serde(default, skip_serializing_if = "Option::is_none", deserialize_with = "deserialize_some", serialize_with = "serialize_some",)]
    pub meid: Option<String>,
}

/// Check-in protocol token update request keys.
#[derive(Debug, Clone, Deserialize, Serialize)]
#[derive(bira::Builder)]

pub struct TokenUpdate {
    /// If 'true', the device is not on console.
    #[serde(rename = "NotOnConsole")]
    #[serde(default, skip_serializing_if = "Option::is_none", deserialize_with = "deserialize_some", serialize_with = "serialize_some",)]
    pub not_on_console: Option<bool>,
    /// The topic the device subscribes to.
    #[serde(rename = "Topic")]
    pub topic: String,
    /// The device's UDID.
    #[serde(rename = "UDID")]
    #[serde(default, skip_serializing_if = "Option::is_none", deserialize_with = "deserialize_some", serialize_with = "serialize_some",)]
    pub udid: Option<String>,
    /// The per-enrollment identifier for the device. Available in macOS 10.15 and iOS 13.0 and later.
    #[serde(rename = "EnrollmentID")]
    #[serde(default, skip_serializing_if = "Option::is_none", deserialize_with = "deserialize_some", serialize_with = "serialize_some",)]
    pub enrollment_id: Option<String>,
    /// The per-enrollment identifier for the user. Available in macOS 10.15 and iOS 13.0 and later.
    #[serde(rename = "EnrollmentUserID")]
    #[serde(default, skip_serializing_if = "Option::is_none", deserialize_with = "deserialize_some", serialize_with = "serialize_some",)]
    pub enrollment_user_id: Option<String>,
    /// On Shared iPad: This is the Managed Apple Account identifier of the user on Shared iPad. It indicates that the token is for the user channel.
    /// On macOS, this is the short name of the user.
    #[serde(rename = "UserShortName")]
    #[serde(default, skip_serializing_if = "Option::is_none", deserialize_with = "deserialize_some", serialize_with = "serialize_some",)]
    pub user_short_name: Option<String>,
    /// On macOS: This is the ID of the user.
    /// On Shared iPad: This is always 'FFFFFFFF-FFFF-FFFF-FFFF-FFFFFFFFFFFF' to indicate that no authentication will occur.
    #[serde(rename = "UserID")]
    #[serde(default, skip_serializing_if = "Option::is_none", deserialize_with = "deserialize_some", serialize_with = "serialize_some",)]
    pub user_id: Option<String>,
    /// The full name of the user.
    #[serde(rename = "UserLongName")]
    #[serde(default, skip_serializing_if = "Option::is_none", deserialize_with = "deserialize_some", serialize_with = "serialize_some",)]
    pub user_long_name: Option<String>,
    /// The Push token for the device.
    #[serde(rename = "Token")]
    pub token: Vec<u8>,
    /// The magic string that has to be included in the push notification message.
    #[serde(rename = "PushMagic")]
    pub push_magic: String,
    /// The data that can be used to unlock the device. If provided, the server should remember this data and send it with when trying to Clear the Passcode.
    #[serde(rename = "UnlockToken")]
    #[serde(default, skip_serializing_if = "Option::is_none", deserialize_with = "deserialize_some", serialize_with = "serialize_some",)]
    pub unlock_token: Option<Vec<u8>>,
    /// If 'true' from the device channel, the device is awaiting a Release Device from Await Configuration MDM command before proceeding through Setup Assistant.
    /// If 'true' from the user channel (Shared iPad only), the device is awaiting a UserConfiguredCommand MDM command before proceeding through Setup Assistant.
    #[serde(rename = "AwaitingConfiguration")]
    #[serde(default, skip_serializing_if = "Option::is_none", deserialize_with = "deserialize_some", serialize_with = "serialize_some",)]
    pub awaiting_configuration: Option<bool>,
}

/// Declarative Management request keys.
#[derive(Debug, Clone, Deserialize, Serialize)]
#[derive(bira::Builder)]

pub struct DeclarativeManagement {
    /// The type of operation the declaration is requesting. This key must be one of these values:
    /// * 'tokens': For fetching synchronization tokens from the server
    /// * 'declaration-items': For fetching the declaration manifest from the server
    /// * 'status': For sending a status report to the server
    /// * 'declaration/…/…': For fetching a specific declaration from the server. Include the declaration type and identifier separated by forward slashes ('/)'.
    #[serde(rename = "Endpoint")]
    pub endpoint: String,
    /// A Base64-encoded JSON object using the SynchronizationTokens schema.
    #[serde(rename = "Data")]
    #[serde(default, skip_serializing_if = "Option::is_none", deserialize_with = "deserialize_some", serialize_with = "serialize_some",)]
    pub data: Option<Vec<u8>>,
    /// The device's UDID.
    #[serde(rename = "UDID")]
    #[serde(default, skip_serializing_if = "Option::is_none", deserialize_with = "deserialize_some", serialize_with = "serialize_some",)]
    pub udid: Option<String>,
    /// The per-enrollment identifier for the device.
    #[serde(rename = "EnrollmentID")]
    #[serde(default, skip_serializing_if = "Option::is_none", deserialize_with = "deserialize_some", serialize_with = "serialize_some",)]
    pub enrollment_id: Option<String>,
    /// A per-enrollment identifier that identifies the user for user enrollments.
    #[serde(rename = "EnrollmentUserID")]
    #[serde(default, skip_serializing_if = "Option::is_none", deserialize_with = "deserialize_some", serialize_with = "serialize_some",)]
    pub enrollment_user_id: Option<String>,
    /// On Shared iPad, this value returns the Managed Apple Account of the user. When present indicates that the token is for the user channel. On macOS, this value always returns the short name of the user.
    #[serde(rename = "UserShortName")]
    #[serde(default, skip_serializing_if = "Option::is_none", deserialize_with = "deserialize_some", serialize_with = "serialize_some",)]
    pub user_short_name: Option<String>,
    /// On macOS, this value always returns the ID of the user. On Shared iPad, this value is always set to FFFFFFFF-FFFF-FFFF-FFFF-FFFFFFFFFFFF to indicate that no authentication will occur.
    #[serde(rename = "UserID")]
    #[serde(default, skip_serializing_if = "Option::is_none", deserialize_with = "deserialize_some", serialize_with = "serialize_some",)]
    pub user_id: Option<String>,
    /// The full name of the user.
    #[serde(rename = "UserLongName")]
    #[serde(default, skip_serializing_if = "Option::is_none", deserialize_with = "deserialize_some", serialize_with = "serialize_some",)]
    pub user_long_name: Option<String>,
}

/// Authenticate network or mobile users with MDM.
#[derive(Debug, Clone, Deserialize, Serialize)]
#[derive(bira::Builder)]

pub struct UserAuthenticate {
    /// The device's UDID (Unique Device ID).
    #[serde(rename = "UDID")]
    pub udid: String,
    /// Local mobile user's GUID or network user's GUID from an Open Directory record.
    #[serde(rename = "UserID")]
    pub user_id: String,
    /// A string provided by the client on second UserAuthenticate request after receiving 'DigestChallenge' from server on first UserAuthenticate request.
    #[serde(rename = "DigestResponse")]
    pub digest_response: String,
}

/// Check-in protocol check out request keys.
#[derive(Debug, Clone, Deserialize, Serialize)]
#[derive(bira::Builder)]

pub struct CheckOut {
    /// The topic to which the device subscribed.
    #[serde(rename = "Topic")]
    pub topic: String,
    /// The device's UDID (Unique Device ID).
    #[serde(rename = "UDID")]
    #[serde(default, skip_serializing_if = "Option::is_none", deserialize_with = "deserialize_some", serialize_with = "serialize_some",)]
    pub udid: Option<String>,
    /// The per-enrollment identifier for the device. Available in macOS 10.15 and iOS 13.0 and later.
    #[serde(rename = "EnrollmentID")]
    #[serde(default, skip_serializing_if = "Option::is_none", deserialize_with = "deserialize_some", serialize_with = "serialize_some",)]
    pub enrollment_id: Option<String>,
}

/// Check-in protocol set bootstrap token data.
#[derive(Debug, Clone, Deserialize, Serialize)]
#[derive(bira::Builder)]

pub struct SetBootstrapToken {
    /// The device's bootstrap token data. If this field is missing or zero length, the bootstrap token should be removed for this device.
    #[serde(rename = "BootstrapToken")]
    #[serde(default, skip_serializing_if = "Option::is_none", deserialize_with = "deserialize_some", serialize_with = "serialize_some",)]
    pub bootstrap_token: Option<Vec<u8>>,
    /// If 'true', the device is awaiting a DeviceConfigured MDM command before proceeding through Setup Assistant.
    #[serde(rename = "AwaitingConfiguration")]
    #[serde(default, skip_serializing_if = "Option::is_none", deserialize_with = "deserialize_some", serialize_with = "serialize_some",)]
    pub awaiting_configuration: Option<bool>,
}

/// Check-in protocol get bootstrap token data.
#[derive(Debug, Clone, Deserialize, Serialize)]
#[derive(bira::Builder)]

pub struct GetBootstrapToken {
    /// If 'true', the device is awaiting a DeviceConfigured MDM command before proceeding through Setup Assistant.
    #[serde(rename = "AwaitingConfiguration")]
    #[serde(default, skip_serializing_if = "Option::is_none", deserialize_with = "deserialize_some", serialize_with = "serialize_some",)]
    pub awaiting_configuration: Option<bool>,
}

/// A command sent by the device during MDM checkin.
#[derive(Debug, Clone, Deserialize, Serialize)]
#[serde(tag = "MessageType")]
pub enum CheckinCommand { 
    #[serde(rename = "GetToken")]
	/// Check-in protocol get token data.
	GetToken(GetToken),
    #[serde(rename = "Authenticate")]
	/// Check-in protocol authenticate request keys.
	Authenticate(Authenticate),
    #[serde(rename = "TokenUpdate")]
	/// Check-in protocol token update request keys.
	TokenUpdate(TokenUpdate),
    #[serde(rename = "DeclarativeManagement")]
	/// Declarative Management request keys.
	DeclarativeManagement(DeclarativeManagement),
    #[serde(rename = "UserAuthenticate")]
	/// Authenticate network or mobile users with MDM.
	UserAuthenticate(UserAuthenticate),
    #[serde(rename = "CheckOut")]
	/// Check-in protocol check out request keys.
	CheckOut(CheckOut),
    #[serde(rename = "SetBootstrapToken")]
	/// Check-in protocol set bootstrap token data.
	SetBootstrapToken(SetBootstrapToken),
    #[serde(rename = "GetBootstrapToken")]
	/// Check-in protocol get bootstrap token data.
	GetBootstrapToken(GetBootstrapToken),
}

impl CheckinCommand { pub fn from_bytes (s : & [u8]) -> Result < Self , plist :: Error > { plist :: from_bytes (s) } pub fn to_string (& self) -> Result < Vec < u8 > , plist :: Error > { let mut buf = Vec :: new () ; plist :: to_writer_xml (& mut buf , self) ? ; Ok (buf) } }fn deserialize_some<'de, D, T>(de: D) -> Result<Option<T>, D::Error>
where
    D: serde::de::Deserializer<'de>,
    T: Deserialize<'de>,
{
    T::deserialize(de).map(Some)
}

fn serialize_some<S, T>(value: &Option<T>, ser: S) -> Result<S::Ok, S::Error>
where
    S: serde::ser::Serializer,
    T: Serialize,
{
    value
        .as_ref()
        .expect(
            r#"`serialize_some` must be used with `skip_serializing_if = "Option::is_none"`"#,
        )
        .serialize(ser)
}