//! This file was generated by [Specta](https://github.com/specta-rs/specta)
use serde::{Deserialize, Serialize};

/// This command allows the server to set settings on the device.
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct SettingsCommand {
    /// An array of dictionaries that contains the settings.
    #[serde(rename = "Settings")]
    pub settings: serde_yaml::Value,
}

/// Clears the Activation Lock bypass code from the device.
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct ClearActivationLockBypassCodeCommand {
}

/// This command requests an UnlockToken from the device.
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct RequestUnlockTokenCommand {
}

/// Sets or clears the recovery lock password (AppleSilicon devices only)
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct SetRecoveryLockCommand {
    /// If the device has a Recovery Lock password set, the system requires the current password.
    #[serde(rename = "CurrentPassword")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub current_password: Option<String>,
    /// The new password for Recovery Lock. Set as an empty string to clear the Recovery Lock password.
    #[serde(rename = "NewPassword")]
    pub new_password: String,
}

/// This command allows the server to install enterprise applications on a device. It provides a more secure version of 'InstallApplication' that specifies a 'ManifestURL'.
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct InstallEnterpriseApplicationCommand {
    /// A dictionary that specifies where to download the app. This value is backward-compatible with the manifest for the InstallApplicationCommand; however, it also allows you to specify 'sha256s' and 'sha256-size' for SHA-256 hashes.
    #[serde(rename = "Manifest")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub manifest: Option<serde_yaml::Value>,
    /// The URL of the app manifest, which needs to begin with 'https:'. The manifest is returned as a property list.
    #[serde(rename = "ManifestURL")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub manifest_url: Option<String>,
    /// An array of DER-encoded certificates to pin the connection when fetching the 'ManifestURL'.
    #[serde(rename = "ManifestURLPinningCerts")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub manifest_url_pinning_certs: Option<serde_yaml::Value>,
    /// If 'true', certificate revocation checks require a positive response when using certificate pinning with 'ManifestURLPinningCerts'.
    #[serde(rename = "PinningRevocationCheckRequired")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub pinning_revocation_check_required: Option<bool>,
    /// If 'true', install the app as a managed app. Otherwise, the system installs the app as unmanaged. If you reinstall a manged app and omit this value or set it to 'false', the app becomes unmanaged.
    /// For manifest-based installs, if 'true', the system only considers apps installed in '/Applications' as managed. In macOS 11 through 13, the system requires that the 'pkg' only contains a single signed app.
    /// Available in macOS 11 and later.
    #[serde(rename = "InstallAsManaged")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub install_as_managed: Option<bool>,
    /// The management flags. The possible values are:
    /// 
    /// * '1': If 'InstallAsManaged' is 'true', remove the app upon removal of the MDM profile.
    /// 
    /// Available in macOS 11 and later.
    #[serde(rename = "ManagementFlags")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub management_flags: Option<i64>,
    /// A dictionary that contains the initial configuration of the app, if you choose to provide it. Available in macOS 11 and later.
    #[serde(rename = "Configuration")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub configuration: Option<serde_yaml::Value>,
    /// The change management state. This value doesn't work with the User Enrollment feature introduced in iOS 13. The only possible value is:
    /// 
    /// * 'Managed': Take management of the app if the user installed it already and 'InstallAsManaged' is 'true'.
    /// 
    /// Available in macOS 11 and later.
    #[serde(rename = "ChangeManagementState")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub change_management_state: Option<String>,
    /// If 'true', the app is an iOS app that can run on an Apple silicon in macOS 11 and later.
    #[serde(rename = "iOSApp")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub i_os_app: Option<bool>,
}

/// Instructs the device to query for active cellular plan eSIM "profiles" at the designated carrier eSIM server URL.
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct RefreshCellularPlansCommand {
    /// The carrier's eSIM server URL to query. Obtain this URL from each carrier separately.
    #[serde(rename = "eSIMServerURL")]
    pub e_sim_server_url: String,
}

/// This command allows the server to remove a profile. This command requires the Profile Installation and Removal Right. It's supported in the user channel.
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct RemoveProfileCommand {
    /// The identifier of the profile to remove.
    #[serde(rename = "Identifier")]
    pub identifier: String,
}

/// Informs the device that it can continue past Setup Assistant and finish login. Only works on Shared iPads that have the AwaitUserConfiguration feature enabled.
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct UserConfiguredCommand {
}

/// Issues LOM requests to devices.
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct LomDeviceRequestCommand {
    /// An array of requests to perform.
    #[serde(rename = "RequestList")]
    pub request_list: serde_yaml::Value,
}

/// This command allows the server to query for installed 3rd party applications.
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct ManagedMediaListCommand {
}

/// This command allows the server to install a provisioning profile. No error occurs if the provisioning profile is already installed. This command requires the Provisioning Profile Installation and Removal right. On macOS, this command is for iOS and iPadOS style provisioning profiles only.
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct InstallProvisioningProfileCommand {
    /// The provisioning profile.
    #[serde(rename = "ProvisioningProfile")]
    pub provisioning_profile: serde_yaml::Value,
}

/// This command allows the server to retrieve the list of installed certificates on the device. The command requires that the server has the Inspect Profile Manifest privilege. For userenrollment, this request will limit to certificates pushed via MDM. Starting with iOS 15.4, the CertificateList command will return a Not Now response prior to the first time a passcode-protected device is unlocked after boot. Between iOS 15.0 and iOS 15.4, devices in that state did not respond with Not Now, but some identity certificates may not have been reported in the response.
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct CertificateListCommand {
    /// If 'true', only include certificates that MDM installed or that are in the same profile as the MDM payload. User-enrolled devices ignore this value and always only include managed certificates. This value is available in iOS 13 and later, macOS 10.15 and later, and tvOS 13 and later.
    #[serde(rename = "ManagedOnly")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub managed_only: Option<bool>,
}

/// This command allows the server to turn on the Declarative Management engine on the device (the first time it is used), or to trigger a Declarative Management synchronization operation.
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct DeclarativeManagementCommand {
    /// The base64-encoded Declarative Management JSON request using a TokensResponse.
    #[serde(rename = "Data")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub data: Option<serde_yaml::Value>,
}

/// This command requires the Device Lock access right. The device will restart immediately.
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct RestartDeviceCommand {
    /// If 'true', the system rebuilds the kernel cache during a device restart. If 'BootstrapTokenAllowedForAuthentication' is 'true' in the SecurityInfoResponse.SecurityInfo response, the device requests the bootstrap token from the MDM server prior to executing this command. This value is available in macOS 11 and later.
    #[serde(rename = "RebuildKernelCache")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub rebuild_kernel_cache: Option<bool>,
    /// If 'RebuildKernelCache' is 'true', this value specifies the paths to kexts to add to the auxiliary kernel cache since the last kernel cache rebuild. If not present, the system only adds previously discovered kexts to the kernel cache. This value is available in macOS 11 and later.
    #[serde(rename = "KextPaths")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub kext_paths: Option<serde_yaml::Value>,
    /// If 'true', notifies the user to restart the device at their convenience. No forced restart occurs unless the device is at 'loginwindow' with no logged-in users. The user can dismiss the notification and ignore the request. No further notifications display unless you resend the command.
    /// This value is available in macOS 11.3 and later.
    #[serde(rename = "NotifyUser")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub notify_user: Option<bool>,
}

/// This command allows the server to ask for the device's location if it is in MDM lost mode.
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct DeviceLocationCommand {
}

/// This commands allows the server to force validation of the free developer and universal provisioning profiles associated with an enterprise app.
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct ValidateApplicationsCommand {
    /// The bundle identifiers of the enterprise apps to include for validation of associated provisioning profiles, if you choose to provide them. Otherwise, validation occurs for the provisioning profiles for the installed managed apps.
    #[serde(rename = "Identifiers")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub identifiers: Option<serde_yaml::Value>,
}

/// Enable Remote Desktop on the device.
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct EnableRemoteDesktopCommand {
}

/// This command allows the server to retrieve the list of installed provisioning profiles on the device. This command requires the Inspect Provisioning Profiles right. On macOS, this command is for iOS and iPadOS style provisioning profiles only.
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct ProvisioningProfileListCommand {
    /// If 'true', only include profiles that MDM has installed. For user enrollments, the device ignores this key and always limits the results to managed profiles. This value is available in iOS 13 and later, and tvOS 13 and later.
    #[serde(rename = "ManagedOnly")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub managed_only: Option<bool>,
}

/// This command allows the server to unlock a local user account.
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct UnlockUserAccountCommand {
    /// The user name of the local account, which can be any local account on the system, not just a managed user account.
    #[serde(rename = "UserName")]
    pub user_name: String,
}

/// This command allows for changing a device's FileVaultMaster password.
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct RotateFileVaultKeyCommand {
    /// The type of FileVault key you want to change the password for. Set this value to 'personal' and set a value for 'Password' in the 'FileVaultUnlock' dictionary to enable unlocking a device with a password. Set this value to 'institutional' and set values for 'PrivateKeyExport' and 'PrivateKeyExportPassword' in the 'FileVaultUnlock' dictionary.
    #[serde(rename = "KeyType")]
    pub key_type: String,
    /// A dictionary that contains FileVault unlock options.
    #[serde(rename = "FileVaultUnlock")]
    pub file_vault_unlock: serde_yaml::Value,
    /// A DER-encoded certificate for creating a new institutional recovery key, which the system requires if 'KeyType' is 'institutional'.
    #[serde(rename = "NewCertificate")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub new_certificate: Option<serde_yaml::Value>,
    /// A DER-encoded certificate for encrypting the new personal recovery key in a wrapper conforming to the IETF Cryptographic Message Syntax (CMS) standard.
    #[serde(rename = "ReplyEncryptionCertificate")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reply_encryption_certificate: Option<serde_yaml::Value>,
}

/// This command returns information about installed extensions for a user.
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct NsextensionMappingsCommand {
}

/// This command allows the server to query for installed 3rd party applications.
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct InstalledApplicationListCommand {
    /// An array of app identifiers. Provide this value to limit the response to only include these apps. This value is available in iOS 7 and later, macOS 10.15 and later, and tvOS 10.2 and later. For a watchOS app, the identifier needs to be the watch's bundle identifier, which differs from the main bundle identifier for the iPhone to which the watch is paired. Obtain the watch's bundle identifier for an app with a watch bundle, in the 'watchBundleId' key that's part of the Content Metadata query. For more information on this query, see Getting App and Book Information (Legacy).
    #[serde(rename = "Identifiers")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub identifiers: Option<serde_yaml::Value>,
    /// If 'true', only get a list of managed apps excluding ones that are managed by Declarative Device Management. This value is available in iOS 7 and later, macOS 10.15 and later, and tvOS 10.2 and later.
    #[serde(rename = "ManagedAppsOnly")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub managed_apps_only: Option<bool>,
    /// An array of strings that represent keys in InstalledApplicationListResponse.InstalledApplicationListItem. If present, the response only contains the keys listed here, except 'Identifier' is always included. If not present, the response contains all keys.
    /// Only request the keys that you need, because some key values can take significant time and power to calculate on the device.
    #[serde(rename = "Items")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub items: Option<serde_yaml::Value>,
}

/// This command requires the Device Lock access right. The device will shut down immediately.
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct ShutDownDeviceCommand {
}

/// Disable Remote Desktop on the device.
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct DisableRemoteDesktopCommand {
}

/// This command allows the server to determine what restrictions are being enforced on the device, and the total sum of all restrictions. This command requires the Restrictions Query access right.
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct RestrictionsCommand {
    /// If 'true', the device reports restrictions from each profile. This value is available in iOS 4 and later, and tvOS 6.1 and later.
    #[serde(rename = "ProfileRestrictions")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub profile_restrictions: Option<bool>,
}

/// This command allows the server to query for specific device information. It's supported in the user channel.
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct DeviceInformationCommand {
    /// An array of query dictionaries to get information about a device.
    #[serde(rename = "Queries")]
    pub queries: serde_yaml::Value,
    /// This specifies a freshness code which appears in the resulting attestation. The value can contain up to 32 bytes of data. If specified, 'Queries' needs to contain 'DevicePropertiesAttestation'.
    /// The MDM server can use this to prove that an attestation was recently generated. The system caches the most recently generated attestation on the device. If omitted or if the value matches the cached attestation, the system returns the cached attestation. To request a new attestation, provide a new freshness code. Requests for new attestations are rate limited. If it has been fewer than 7 days since the system generated an attestation, the device returns the cached attestation rather than generating a new one.
    /// Available in iOS 16 and later, macOS 14 and later, tvOS 16 and later, and watchOS 10 and later. See the DeviceInformation attestation hardware support note for hardware requirements.
    #[serde(rename = "DeviceAttestationNonce")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub device_attestation_nonce: Option<serde_yaml::Value>,
}

/// This command allows the server to schedule an OS update.
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct ScheduleOSUpdateCommand {
    /// An array of dictionaries specifying the updates to download or install. If this value is missing, the device applies the default behavior for handling updates. This command is ignored and an informational error is returned if a Software Update is actively managed via a Declarative Device Management 'Software Update Enforcement Policy' configuration, as the Declarative Device Management configuration takes precedence.
    #[serde(rename = "Updates")]
    pub updates: serde_yaml::Value,
}

/// Changes or clears the firmware password for the device.
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct SetFirmwarePasswordCommand {
    /// The current password, which you must set if the device has a firmware password.
    #[serde(rename = "CurrentPassword")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub current_password: Option<String>,
    /// The new firmware password. Set to an empty string to clear the password. The characters in this value must consist of low-ASCII, printable characters ('0x20' through '0x7E') to ensure that all characters are enterable on the EFI login screen.
    #[serde(rename = "NewPassword")]
    pub new_password: String,
    /// If 'true', enable ROMs.
    #[serde(rename = "AllowOroms")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub allow_oroms: Option<bool>,
}

/// This command allows the server to tell the device to play a sound if it is in MDM Lost Mode. The sound will play until the device is either removed from Lost Mode or a user disables the sound from the device.
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct PlayLostModeSoundCommand {
}

/// This command allows the server to remove a provisioning profile. This command requires the Provisioning Profile Installation and Removal right. On macOS, this command is for iOS and iPadOS style provisioning profiles only.
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct RemoveProvisioningProfileCommand {
    /// The unique identifier of the provisioning profile to remove.
    #[serde(rename = "UUID")]
    pub uuid: String,
}

/// Queries the device for a list of available OS updates. On OS X, a ScheduleOSUpdateScan must be performed to update the results returned by this query.
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct AvailableOSUpdatesCommand {
}

/// Returns information about the active NSExtensions for a particular user.
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct ActiveNSExtensionsCommand {
    /// An array of extension points. If you choose to provide this value, the response only includes the app extensions for the extension points you specify.
    #[serde(rename = "FilterExtensionPoints")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub filter_extension_points: Option<serde_yaml::Value>,
}

/// This command allows the server to clear the passcode on the device. This command requires the Device Lock and Passcode Removal right.
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct ClearPasscodeCommand {
    /// The unlock token value that the device provides in its 'TokenUpdateMessage' check-in message.
    #[serde(rename = "UnlockToken")]
    pub unlock_token: serde_yaml::Value,
}

/// Verifies the device's firmware password.
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct VerifyFirmwarePasswordCommand {
    /// The password to verify.
    #[serde(rename = "Password")]
    pub password: String,
}

/// This command prompts the user to share their screen using AirPlay mirroring.
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct RequestMirroringCommand {
    /// The name of the AirPlay Mirroring destination.
    #[serde(rename = "DestinationName")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub destination_name: Option<String>,
    /// The hardware address of the AirPlay Mirroring destination that identifies the device, in the format 'xx:xx:xx:xx:xx'. This value isn't case-sensitive.
    #[serde(rename = "DestinationDeviceID")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub destination_device_id: Option<String>,
    /// The number of seconds, from '10' to '300', for the device to spend searching for the destination. The default value is '30'.
    #[serde(rename = "ScanTime")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub scan_time: Option<i64>,
    /// The screen-sharing password that the device uses when connecting to the destination.
    #[serde(rename = "Password")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub password: Option<String>,
}

/// This command allows the server to force the current user to logout.
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct LogOutUserCommand {
}

/// This command queries the device for application feedback information. This command requires the App Management right.
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct ManagedApplicationFeedbackCommand {
    /// The bundle identifiers of the managed apps.
    #[serde(rename = "Identifiers")]
    pub identifiers: serde_yaml::Value,
    /// If 'true', delete the app's feedback dictionary after the server reads it. Apps that are managed by Declarative Device Management will be ignored.
    #[serde(rename = "DeleteFeedback")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub delete_feedback: Option<bool>,
}

/// This command allows the host to install a configuration profile. The profile may be encrypted using any installed identity certificate. The profile may also be signed. This command requires the Profile Installation and Removal right. It's supported in the user channel.
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct InstallProfileCommand {
    /// The profile to install, which you can encrypt using any identity certificate installed on the device. You can also sign the profile.
    #[serde(rename = "Payload")]
    pub payload: serde_yaml::Value,
}

/// Queries the device for LOM setup information such as IP addresses, protocol version, etc.
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct LomSetupRequestCommand {
}

/// Allows changing the password of a local admin account that was created by Setup Assistant during DEP enrollment via the AccountConfiguration command.
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct SetAutoAdminPasswordCommand {
    /// The unique identifier of the local administrator account. If this value doesn't match the GUID of an administrator account that MDM created during Device Enrollment Program (DEP) enrollment, the command returns an error.
    #[serde(rename = "GUID")]
    pub guid: String,
    /// The precreated salted SHA-512 PBKDF2 password hash for the account.
    /// Create this hash on the server using the CommonCrypto libraries, or equivalent, as a salted SHA-512 PBKDF2 dictionary that contains these elements:
    /// * 'entropy': The derived key from the password hash; for example, from 'CCKeyDerivationPBKDF()'
    /// * 'salt': The 32-byte randomized salt; for example, from 'CCRandomCopyBytes()'
    /// * 'iterations:' The number of iterations; for example, from 'CCCalibratePBKDF()' using a minimum hash time of 100 milliseconds, or if unknown, a number in the range of 20,000 to 40,000 iterations
    /// Place the dictionary that contains these elements into an outer dictionary with the key 'SALTED-SHA512-PBKDF2'. Convert this dictionary to binary data before setting it as the value for 'passwordHash'.
    #[serde(rename = "passwordHash")]
    pub password_hash: serde_yaml::Value,
}

/// This command allows the server to delete a user that has an active account on the device.
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct DeleteUserCommand {
    /// The user name of the account to delete. This key is required when the value for 'DeleteAllUsers' is absent or 'false'.
    #[serde(rename = "UserName")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub user_name: Option<String>,
    /// If 'true', the system deletes the account even if the user has data that's pending sync to the cloud. This value is available on iOS 9.3 and later.
    #[serde(rename = "ForceDeletion")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub force_deletion: Option<bool>,
    /// If 'true', the system attempts to delete all users from the device. If 'ForceDeletion' is 'false', the system generates an error instead and doesn't delete users who have data that's pending sync. This value is available in iOS 14 and later.
    #[serde(rename = "DeleteAllUsers")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub delete_all_users: Option<bool>,
}

/// This command allows an MDM server to remove managed media. This command returns Acknowledged even if the item is not found.
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct RemoveMediaCommand {
    /// The media type, which can only be 'Book'.
    #[serde(rename = "MediaType")]
    pub media_type: String,
    /// The book's iTunes Store identifier.
    #[serde(rename = "iTunesStoreID")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub i_tunes_store_id: Option<String>,
    /// The book's persistent identifier in reverse-DNS form; for example, 'com.acme.manuals.training'.
    #[serde(rename = "PersistentID")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub persistent_id: Option<String>,
}

/// This command can be sent to the device to have it create the local administrator account (thereby skipping the page to create this account in Setup Assistant)
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct AccountConfigurationCommand {
    /// If 'true', Setup Assistant skips the user interface for setting up primary accounts and disables autologin. If 'true', you must specify a value for 'AutoSetupAdminAccounts'.
    #[serde(rename = "SkipPrimarySetupAccountCreation")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub skip_primary_setup_account_creation: Option<bool>,
    /// If 'true', Setup Assistant creates the primary accounts as regular users, and you must specify a value for 'AutoSetupAdminAccounts'.
    #[serde(rename = "SetPrimarySetupAccountAsRegularUser")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub set_primary_setup_account_as_regular_user: Option<bool>,
    /// The full name for the primary account. If present, Setup Assistant uses this value to prefill the Full Name field. However, Setup Assistant ignores this value if 'DontAutoPopulatePrimaryAccountInfo' is 'true'. This value is available in macOS 10.15 and later.
    #[serde(rename = "PrimaryAccountFullName")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub primary_account_full_name: Option<String>,
    /// The account name for the primary account. If present, Setup Assistant uses this value to prefill the User Name field. However, Setup Assistant ignores this value if 'DontAutoPopulatePrimaryAccountInfo' is 'true'. This value is available in macOS 10.15 and later.
    #[serde(rename = "PrimaryAccountUserName")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub primary_account_user_name: Option<String>,
    /// If 'true', Setup Assistant ignores the primary account information and requires the user to enter that information. If 'false', Setup Assistant prefills the Full Name field with 'PrimaryAccountFullName' and the User Name field with 'PrimaryAccountUserName'. This value is available in macOS 10.15 and later.
    #[serde(rename = "DontAutoPopulatePrimaryAccountInfo")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub dont_auto_populate_primary_account_info: Option<bool>,
    /// If 'true', and you provide values for 'PrimaryAccountFullName' or 'PrimaryAccountUserName', Setup Assistant disables editing for the corresponding fields. 'DontAutoPopulatePrimaryAccountInfo' must also be 0 (or missing).
    /// If the user's password is also available from authentication through ConfigurationURL, Setup Assistant automatically creates the primary account with that information and skips showing the user interface to view or edit these fields.
    /// This value is available in macOS 10.15 and later.
    #[serde(rename = "LockPrimaryAccountInfo")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub lock_primary_account_info: Option<bool>,
    /// A dictionary that describes the administrator account to create with Setup Assistant, which uses the first element and ignores additional elements.
    #[serde(rename = "AutoSetupAdminAccounts")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub auto_setup_admin_accounts: Option<serde_yaml::Value>,
    /// If present, this is the short name of the local account to manage, which can also be the account that results from setting 'AutoSetupAdminAccounts' to 'true'. Otherwise, only the local account that Setup Assistant creates is a managed account. This value is available in macOS 11 and later.
    #[serde(rename = "ManagedLocalUserShortName")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub managed_local_user_short_name: Option<String>,
}

/// Verifies the device's recovery lock password. (AppleSilicon devices only)
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct VerifyRecoveryLockCommand {
    /// The password to verify.
    #[serde(rename = "Password")]
    pub password: String,
}

/// This command allows the server to take the device out of MDM lost mode.
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct DisableLostModeCommand {
}

/// Informs the device that it can continue past DEP enrollment. Only works on devices in DEP that have their cloud configuration set to await configuration.
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct DeviceConfiguredCommand {
}

/// If a redemption code is needed during app installation, the server can use this command to complete the app installation.
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct ApplyRedemptionCodeCommand {
    /// The bundle identifier of the app.
    #[serde(rename = "Identifier")]
    pub identifier: String,
    /// The redemption code that applies to the app pending installation.
    #[serde(rename = "RedemptionCode")]
    pub redemption_code: String,
}

/// Requests that the device perform a background scan for OS updates.
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct ScheduleOSUpdateScanCommand {
    /// If 'true', force a scan to start immediately. Otherwise, the scan starts at a system-determined time.
    #[serde(rename = "Force")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub force: Option<bool>,
}

/// This command allows a server to invite a user to join a program.
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct InviteToProgramCommand {
    /// The program's identifier, which can only be 'com.apple.cloudvpp'.
    #[serde(rename = "ProgramID")]
    pub program_id: String,
    /// The Volume Purchase Program (VPP) invitation URL.
    #[serde(rename = "InvitationURL")]
    pub invitation_url: String,
}

/// This command allows the server to install an application on a device. If the app is already being managed, this command will update the app. Prior to iOS 16.0 and tvOS 16.0, this command would return NotNow when Setup Assistant was running. Starting in iOS 16.0 and tvOS 16.0, the command may be sent to supervised devices during Setup Assistant. However, you should only attempt to install device-based VPP apps or enterprise apps while in the awaiting configuration state, as the device will likely not yet have an App Store account configured, and thus commands that depend on one will fail.
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct InstallApplicationCommand {
    /// The app's iTunes Store identifier.
    #[serde(rename = "iTunesStoreID")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub i_tunes_store_id: Option<i64>,
    /// The app's bundle identifier.
    /// For a watchOS app, the identifier needs to be the watch's bundle identifier, which differs from the main bundle identifier for the iPhone to which the watch is paired. Obtain the watch's bundle identifier for an app with a watch bundle, in the 'watchBundleId' key that's part of the Content Metadata query. For more information on this query, see Getting App and Book Information (Legacy).
    #[serde(rename = "Identifier")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub identifier: Option<String>,
    /// A dictionary that contains the app installation options.
    #[serde(rename = "Options")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub options: Option<serde_yaml::Value>,
    /// The URL of the app manifest, which needs to begin with 'https:'. The manifest is returned as a property list.
    #[serde(rename = "ManifestURL")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub manifest_url: Option<String>,
    /// A bitwise OR of the management flags. The possible values are:
    /// 
    /// * '1': If 'InstallAsManaged' is 'true', remove the app upon removal of the MDM profile.
    /// * '4': Prevent backup of app data.
    /// * '5': Both '1' and '4'.
    /// 
    /// Available in iOS 5 and later, macOS 11 and later, and tvOS 10.2 and later.
    #[serde(rename = "ManagementFlags")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub management_flags: Option<i64>,
    /// A dictionary that contains the initial configuration of the app, if you choose to provide it. Available in iOS 7 and later, macOS 11 and later, and tvOS 10.2 and later.
    #[serde(rename = "Configuration")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub configuration: Option<serde_yaml::Value>,
    /// A dictionary that contains the initial attributes of the app, if you choose to provide it. Available in iOS 7 and later, and tvOS 10.2 and later.
    #[serde(rename = "Attributes")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub attributes: Option<serde_yaml::Value>,
    /// The change management state. The only possible value is:
    /// 
    /// * 'Managed': Take management of the app if the user installed it already. This also requires that you pass 'true' for 'InstallAsManaged'.
    /// 
    /// This value doesn't work with the User Enrollment feature introduced in iOS 13. Available in iOS 9 and later, macOS 11 and later, and tvOS 10.2 and later.
    #[serde(rename = "ChangeManagementState")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub change_management_state: Option<String>,
    /// If 'true', install the app as a managed app. Otherwise, the system installs the app as unmanaged. If you reinstall a manged app and omit this value or set it to 'false', the app becomes unmanaged.
    /// For manifest-based installs, if 'true', the system only considers apps installed in '/Applications' as managed. In macOS 11 through 13, the system requires that the 'pkg' only contains a single signed app.
    /// Available in macOS 11 and later.
    #[serde(rename = "InstallAsManaged")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub install_as_managed: Option<bool>,
    /// If 'true', the app is an iOS app that can run on an Apple silicon in macOS 11 and later.
    #[serde(rename = "iOSApp")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub i_os_app: Option<bool>,
}

/// Queries the device for the status of software updates.
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct OsUpdateStatusCommand {
}

/// This command stops AirPlay mirroring.
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct StopMirroringCommand {
}

/// This command allows the server to query for information about Content Caching.
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct ContentCachingInformationCommand {
}

/// This command allows the server to query for a list of users that have an active account on the device.
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct UserListCommand {
}

/// This command allows a server to remove a managed app.
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct RemoveApplicationCommand {
    /// The bundle identifier of the managed app.
    /// For a watchOS app, the identifier needs to be the watch's bundle identifier, which differs from the main bundle identifier for the iPhone to which the watch is paired. Obtain the watch's bundle identifier for an app with a watch bundle, in the 'watchBundleId' key that's part of the Content Metadata query. For more information on this query, see Getting App and Book Information (Legacy).
    #[serde(rename = "Identifier")]
    pub identifier: String,
}

/// This command allows the server to install a book on a device. If the book is already being managed, this command will update the book.
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct InstallMediaCommand {
    /// The book's iTunes Store identifier.
    #[serde(rename = "iTunesStoreID")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub i_tunes_store_id: Option<i64>,
    /// The URL to retrieve the book. This value is available in iOS 8 and later.
    #[serde(rename = "MediaURL")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub media_url: Option<String>,
    /// The media type, which can only be 'Book'.
    #[serde(rename = "MediaType")]
    pub media_type: String,
    /// The book's persistent identifier in reverse-DNS form; for example, 'com.acme.manuals.training'. This value is available in iOS 8 and later.
    #[serde(rename = "PersistentID")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub persistent_id: Option<String>,
    /// The kind of the media, which can be one of the following values:
    /// * 'pdf': A PDF file
    /// * 'epub': An EPUB file in 'gzip' format.
    /// * 'ibooks': An iBooks Author file in 'gzip' format.
    /// If you omit this value, its value is the file extension in the URL. This value is available in iOS 8 and later.
    #[serde(rename = "Kind")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub kind: Option<String>,
    /// The book's version number. This value is available in iOS 8 and later.
    #[serde(rename = "Version")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub version: Option<String>,
    /// The name of the book's author. This value is available in iOS 8 and later.
    #[serde(rename = "Author")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub author: Option<String>,
    /// The book's title. This value is available in iOS 8 and later.
    #[serde(rename = "Title")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
}

/// Queries managed application attributes. Attributes can be set on managed apps. These attributes can be changed over time.
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct ManagedApplicationAttributesCommand {
    /// The bundle identifiers of the managed apps.
    /// For a watchOS app, the identifier needs to be the watch's bundle identifier, which differs from the main bundle identifier for the iPhone to which the watch is paired. Obtain the watch's bundle identifier for an app with a watch bundle, in the 'watchBundleId' key that's part of the Content Metadata query. For more information on this query, see Getting App and Book Information (Legacy).
    #[serde(rename = "Identifiers")]
    pub identifiers: serde_yaml::Value,
}

/// This command clears the restrictions passcode, either disabling parental controls or allowing you to edit them.
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct ClearRestrictionsPasswordCommand {
}

/// This command allows the MDM server to query for the profiles installed on the device. This command requires the Inspect Profile Manifest right. It's supported on the user channel.
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct ProfileListCommand {
    /// If 'true', only include profiles that MDM has installed. For user enrollments, the device ignores this key and always limits the results to managed profiles. This value is available in iOS 13 and later, macOS 10.5 and later, and tvOS 13 and later.
    #[serde(rename = "ManagedOnly")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub managed_only: Option<bool>,
}

/// Retrieves the Activation Lock bypass code from the device.
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct ActivationLockBypassCodeCommand {
}

/// This command allows the server to immediately lock the device. This command requires the Device Lock and Passcode Removal right.
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct DeviceLockCommand {
    /// The message to display on the Lock screen of the device. This value doesn't apply to a shared iPad device. This value is available in iOS 4 and later, and macOS 10.14 and later.
    #[serde(rename = "Message")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    /// The phone number to display on the Lock screen. This value doesn't apply to a shared iPad device. This value is available in iOS 7 and later and macOS 11.5 and later (for Apple silicon devices only).
    #[serde(rename = "PhoneNumber")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub phone_number: Option<String>,
    /// The six-character PIN for Find My. This value is available in macOS 10.8 and later.
    #[serde(rename = "PIN")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub pin: Option<String>,
}

/// This command allows the server to put the device in MDM lost mode, with a message, phone number, and footnote text. A message or phone number must be provided.
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct EnableLostModeCommand {
    /// If present, display this text on the Lock screen. You must provide this value if you don't provide a value for 'PhoneNumber'.
    #[serde(rename = "Message")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    /// If present, display this phone number on the Lock screen. You must provide this value if you don't provide a value for 'Message'.
    #[serde(rename = "PhoneNumber")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub phone_number: Option<String>,
    /// If present, display this text in place of Slide to Unlock.
    #[serde(rename = "Footnote")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub footnote: Option<String>,
}

/// This command queries the device for the current configuration of managed applications. This command requires the App Management right. macOS supports this command as of 10.15, on the device channel and for User Enrollments only, because Settings->ApplicationConfiguration is supported. Since macOS does not support Managed Applications, this command can be used for any bundle identifier.
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct ManagedApplicationConfigurationCommand {
    /// The bundle identifiers of the managed apps.
    /// For a watchOS app, the identifier needs to be the watch's bundle identifier, which differs from the main bundle identifier for the iPhone to which the watch is paired. Obtain the watch's bundle identifier for an app with a watch bundle, in the 'watchBundleId' key that's part of the Content Metadata query. For more information on this query, see Getting App and Book Information (Legacy).
    #[serde(rename = "Identifiers")]
    pub identifiers: serde_yaml::Value,
}

/// This command allows the server to remotely erase the device. This command requires the Device Erase right.
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct EraseDeviceCommand {
    /// If 'true', preserve the data plan on an iPhone or iPad with eSIM functionality, if one exists. This value is available in iOS 11 and later.
    #[serde(rename = "PreserveDataPlan")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub preserve_data_plan: Option<bool>,
    /// If 'true', disable Proximity Setup on the next reboot and skip the pane in Setup Assistant. This value is available in iOS 11 and later. Prior to iOS 14, don't use this option with any other option.
    #[serde(rename = "DisallowProximitySetup")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub disallow_proximity_setup: Option<bool>,
    /// The six-character PIN for Find My. This value is available in macOS 10.8 and later.
    #[serde(rename = "PIN")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub pin: Option<String>,
    /// This key defines the fallback behavior for erasing a device.
    /// In macOS 12 and later, this command uses Erase All Content and Settings (EACS) on Mac computers with the Apple M1 chip or the Apple T2 Security Chip. On those devices, if EACS can't run, the device can use obliteration (macOS 11.x behavior). This key has no effect on machines prior to the T2 chip. For a list of supported macs, see Mac models with the Apple T2 Security Chip <https://support.apple.com/en-us/HT208862>.
    /// Upon receiving this command, the device performs preflight checks to determine if the device is in a state that allows EACS. The 'status' of the EraseDeviceResponse is either 'Acknowledged' or 'Error'.
    /// The following values define the device's fallback behavior:
    /// 
    /// * 'DoNotObliterate': If EACS preflight fails, the device responds to the server with an 'Error' status and doesn't attempt to erase itself.
    /// If EACS preflight succeeds but EACS fails, then the device doesn't attempt to erase itself.
    /// * 'ObliterateWithWarning': If EACS preflight fails, the device responds with an 'Acknowledged' status and then attempts to erase itself.
    /// If EACS preflight succeeds but EACS fails, then the device attempts to erase itself.
    /// * 'Always': The system doesn't attempt EACS. T2 and later devices always obliterate.
    /// * 'Default': If EACS preflight fails, the device responds to the server with an 'Error' status and then attempts to erase itself.
    /// If EACS preflight succeeds but EACS fails, then the device attempts to erase itself.
    #[serde(rename = "ObliterationBehavior")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub obliteration_behavior: Option<String>,
    /// The configuration settings for Return to Service. This value is available in iOS 17 and later and with Shared iPad and tvOS 18 and later.
    #[serde(rename = "ReturnToService")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub return_to_service: Option<serde_yaml::Value>,
}

/// This command queries the device for security-related information. Queries are available if the MDM host has the Security Query right.
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct SecurityInfoCommand {
}

/// This command allows the server to query the status of managed apps. Certain statuses are transient. Once they are reported to the server, the entries for the apps are removed from the next query. macOS supports this command on the user channel starting with macOS 11.3.
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct ManagedApplicationListCommand {
    /// The bundle identifiers of the managed apps to include in the response.
    /// For a watchOS app, the identifier needs to be the watch's bundle identifier, which differs from the main bundle identifier for the iPhone to which the watch is paired. Obtain the watch's bundle identifier for an app with a watch bundle, in the 'watchBundleId' key that's part of the Content Metadata query. For more information on this query, see Getting App and Book Information (Legacy).
    #[serde(rename = "Identifiers")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub identifiers: Option<serde_yaml::Value>,
}

