//! This file was generated by [Specta](https://github.com/specta-rs/specta)
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Deserialize, Serialize)]
pub enum ErrorCodeSoftwareUpdateRequiredcode { 
    #[serde(rename = "com.apple.softwareupdate.required")]
	ComAppleSoftwareupdateRequired,
}

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct ErrorCodeSoftwareUpdateRequireddetailRequireBetaProgram {
    #[serde(rename = "Description")]
    pub description: String,
    #[serde(rename = "Token")]
    pub token: String,
}

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct ErrorCodeSoftwareUpdateRequireddetail {
    #[serde(rename = "OSVersion")]
    pub os_version: String,
    #[serde(rename = "BuildVersion")]
    #[serde(default, skip_serializing_if = "Option::is_none", deserialize_with = "deserialize_some", serialize_with = "serialize_some",)]
    pub build_version: Option<String>,
    #[serde(rename = "RequireBetaProgram")]
    #[serde(default, skip_serializing_if = "Option::is_none", deserialize_with = "deserialize_some", serialize_with = "serialize_some",)]
    pub require_beta_program: Option<ErrorCodeSoftwareUpdateRequireddetailRequireBetaProgram>,
}

/// Error response for software update required.
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct ErrorCodeSoftwareUpdateRequired {
    /// Indicates that a software update is required before enrollment and setup can proceed.
    pub code: ErrorCodeSoftwareUpdateRequiredcode,
    /// The description of the error. This will only be used by the client for logging purposes and will not be displayed to the user.
    #[serde(default, skip_serializing_if = "Option::is_none", deserialize_with = "deserialize_some", serialize_with = "serialize_some",)]
    pub description: Option<String>,
    /// A description of the error suitable for displaying to the user. If needed, the client will make a best-effort attempt to display the message, but may not be able to, due to local conditions.
    #[serde(default, skip_serializing_if = "Option::is_none", deserialize_with = "deserialize_some", serialize_with = "serialize_some",)]
    pub message: Option<String>,
    /// A dictionary of additional data specific to the error code.
    pub details: ErrorCodeSoftwareUpdateRequireddetail,
}

#[derive(Debug, Clone, Deserialize, Serialize)]
pub enum ErrorUnrecognizedDevicecode { 
    #[serde(rename = "com.apple.unrecognized.device")]
	ComAppleUnrecognizedDevice,
}

/// Error response for unrecognized device.
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct ErrorUnrecognizedDevice {
    /// Indicates that the device is not recognized by the server, causing the device to unenroll from MDM.
    pub code: ErrorUnrecognizedDevicecode,
    /// The description of the error. This will only be used by the client for logging purposes and will not be displayed to the user.
    #[serde(default, skip_serializing_if = "Option::is_none", deserialize_with = "deserialize_some", serialize_with = "serialize_some",)]
    pub description: Option<String>,
    /// A description of the error suitable for displaying to the user. If needed, the client will make a best-effort attempt to display the message, but may not be able to, due to local conditions.
    #[serde(default, skip_serializing_if = "Option::is_none", deserialize_with = "deserialize_some", serialize_with = "serialize_some",)]
    pub message: Option<String>,
}

#[derive(Debug, Clone, Deserialize, Serialize)]
pub enum ErrorCodePairingTokenMissingcode { 
    #[serde(rename = "com.apple.watch.pairing.token.missing")]
	ComAppleWatchPairingTokenMissing,
}

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct ErrorCodePairingTokenMissingdetail {
    #[serde(rename = "security-token")]
    pub security_token: String,
}

/// Error response for missing pairing token.
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct ErrorCodePairingTokenMissing {
    /// Indicates that pairing token required to enroll a watch is missing.
    pub code: ErrorCodePairingTokenMissingcode,
    /// The description of the error. This will only be used by the client for logging purposes and will not be displayed to the user.
    #[serde(default, skip_serializing_if = "Option::is_none", deserialize_with = "deserialize_some", serialize_with = "serialize_some",)]
    pub description: Option<String>,
    /// A description of the error suitable for displaying to the user. If needed, the client will make a best-effort attempt to display the message, but may not be able to, due to local conditions.
    #[serde(default, skip_serializing_if = "Option::is_none", deserialize_with = "deserialize_some", serialize_with = "serialize_some",)]
    pub message: Option<String>,
    /// A dictionary of additional data specific to the error code.
    pub details: ErrorCodePairingTokenMissingdetail,
}

#[derive(Debug, Clone, Deserialize, Serialize)]
pub enum ErrorWellKnownFailedcode { 
    #[serde(rename = "com.apple.well-known.failed")]
	ComAppleWellKnownFailed,
}

/// Error response for well-known failed
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct ErrorWellKnownFailed {
    /// Indicates that the well-known request has failed.
    pub code: ErrorWellKnownFailedcode,
    /// The description of the error. This will only be used by the client for logging purposes and will not be displayed to the user.
    #[serde(default, skip_serializing_if = "Option::is_none", deserialize_with = "deserialize_some", serialize_with = "serialize_some",)]
    pub description: Option<String>,
    /// A description of the error suitable for displaying to the user. If needed, the client will make a best-effort attempt to display the message, but may not be able to, due to local conditions.
    #[serde(default, skip_serializing_if = "Option::is_none", deserialize_with = "deserialize_some", serialize_with = "serialize_some",)]
    pub message: Option<String>,
}

fn deserialize_some<'de, D, T>(de: D) -> Result<Option<T>, D::Error>
where
    D: serde::de::Deserializer<'de>,
    T: Deserialize<'de>,
{
    T::deserialize(de).map(Some)
}

fn serialize_some<S, T>(value: &Option<T>, ser: S) -> Result<S::Ok, S::Error>
where
    S: serde::ser::Serializer,
    T: Serialize,
{
    value
        .as_ref()
        .expect(
            r#"`serialize_some` must be used with `skip_serializing_if = "Option::is_none"`"#,
        )
        .serialize(ser)
}