//! This file was generated by [Specta](https://github.com/specta-rs/specta)
use serde::{Deserialize, Serialize};

/// Error response for software update required.
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct ErrorCodeSoftwareUpdateRequired {
    /// Indicates that a software update is required before enrollment and setup can proceed.
    pub code: String,
    /// The description of the error. This will only be used by the client for logging purposes and will not be displayed to the user.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// A description of the error suitable for displaying to the user. If needed, the client will make a best-effort attempt to display the message, but may not be able to, due to local conditions.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    /// A dictionary of additional data specific to the error code.
    pub details: serde_yaml::Value,
}

/// Error response for unrecognized device.
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct ErrorUnrecognizedDevice {
    /// Indicates that the device is not recognized by the server, causing the device to unenroll from MDM.
    pub code: String,
    /// The description of the error. This will only be used by the client for logging purposes and will not be displayed to the user.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// A description of the error suitable for displaying to the user. If needed, the client will make a best-effort attempt to display the message, but may not be able to, due to local conditions.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
}

/// Error response for missing pairing token.
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct ErrorCodePairingTokenMissing {
    /// Indicates that pairing token required to enroll a watch is missing.
    pub code: String,
    /// The description of the error. This will only be used by the client for logging purposes and will not be displayed to the user.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// A description of the error suitable for displaying to the user. If needed, the client will make a best-effort attempt to display the message, but may not be able to, due to local conditions.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    /// A dictionary of additional data specific to the error code.
    pub details: serde_yaml::Value,
}

/// Error response for well-known failed
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct ErrorWellKnownFailed {
    /// Indicates that the well-known request has failed.
    pub code: String,
    /// The description of the error. This will only be used by the client for logging purposes and will not be displayed to the user.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// A description of the error suitable for displaying to the user. If needed, the client will make a best-effort attempt to display the message, but may not be able to, due to local conditions.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
}

