//! This file was generated by [Specta](https://github.com/specta-rs/specta)
use serde::{Deserialize, Serialize};

/// The definition of the ManifestURL property list that specifies where a package is to be downloaded from, and provides hashes to verify the integrity of the package
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct ManifestURL {
    /// An array of dictionaries representing what the manifest will install
    pub items: serde_yaml::Value,
}

/// The definition of all the available skip keys
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct SkipKey {
    /// The key to skip the Accessibility pane, when creating additional users. This key is not available in macOS.
    #[serde(rename = "Accessibility")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub accessibility: Option<String>,
    /// The key to skip the Action Button configuration pane. This key is available in iOS 17 and later.
    #[serde(rename = "ActionButton")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub action_button: Option<String>,
    /// If the Restore pane isn't skipped, this is the key to remove the Move from Android option in the Restore pane on iOS. This key is available in iOS 9 and later.
    #[serde(rename = "Android")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub android: Option<String>,
    /// The key to skip the Choose Your Look screen. This key is available in iOS 13+ and macOS 10.14 and later.
    #[serde(rename = "Appearance")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub appearance: Option<String>,
    /// The key to skip Apple Account setup. This key is available in iOS 7.0+, tvOS 10.2 and later, and macOS 10.9 and later.
    #[serde(rename = "AppleID")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub apple_id: Option<String>,
    /// The key to skip the App Store pane. This key is available in iOS 14.3 and later, and macOS 11.1 and later.
    #[serde(rename = "AppStore")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub app_store: Option<String>,
    /// The key to skip biometric setup. This key is available in iOS 8.1 and later, and macOS 10.12.4 and later.
    #[serde(rename = "Biometric")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub biometric: Option<String>,
    /// The key to skip the Camera Button pane. This key is available in iOS 18 and later.
    #[serde(rename = "CameraButton")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub camera_button: Option<String>,
    /// The key to skip Device to Device Migration pane. This key is available in iOS 13 and later.
    #[serde(rename = "DeviceToDeviceMigration")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub device_to_device_migration: Option<String>,
    /// The key to skip the App Analytics pane. This key is available in iOS 7 and later, tvOS 10.2 and later, and macOS 10.9 and later.
    #[serde(rename = "Diagnostics")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub diagnostics: Option<String>,
    /// The key to skip DisplayTone setup. This key is available in iOS 9.3.2 and later, and macOS 10.13.6 and later, and deprecated in iOS 15 and macOS 12.
    #[serde(rename = "DisplayTone")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub display_tone: Option<String>,
    /// The key to skip the Lockdown Mode pane if an Apple Account is set up. Available in iOS 17.1 and later, and macOS 14 and later.
    #[serde(rename = "EnableLockdownMode")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub enable_lockdown_mode: Option<String>,
    /// The key to disable the FileVault Setup Assistant screen in macOS. This key is available in macOS 10.10 and later.
    #[serde(rename = "FileVault")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub file_vault: Option<String>,
    /// The key to skip the Meet the New Home Button screen on iPhone 7, iPhone 7 Plus, iPhone 8, iPhone 8 Plus, and iPhone SE. This key is available in iOS 10 and later, and deprecated in iOS 15.
    #[serde(rename = "HomeButtonSensitivity")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub home_button_sensitivity: Option<String>,
    /// The key to skip the iCloud Analytics screen. This key is available in macOS 10.12.4 and later.
    #[serde(rename = "iCloudDiagnostics")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub i_cloud_diagnostics: Option<String>,
    /// The key to skip the iCloud Documents and Desktop screen in macOS. This key is available in macOS 10.13.4 and later.
    #[serde(rename = "iCloudStorage")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub i_cloud_storage: Option<String>,
    /// The key to skip the iMessage and FaceTime screen in iOS. This key is available in iOS 12 and later.
    #[serde(rename = "iMessageAndFaceTime")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub i_message_and_face_time: Option<String>,
    /// The key to skip the Intelligence pane. This key is available in iOS 18 and later and macOS 15 and later.
    #[serde(rename = "Intelligence")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub intelligence: Option<String>,
    /// The key to skip the Keyboard pane. This pane isn't always skippable because it appears before the device retrieves the Cloud Configuration from the server. This key is available in iOS 13 and later.
    #[serde(rename = "Keyboard")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub keyboard: Option<String>,
    /// The key to disable Location Services. This key is available in iOS 7 and later, and macOS 10.11 and later.
    #[serde(rename = "Location")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub location: Option<String>,
    /// The key to skip the iMessage pane. This key is available in iOS 10 and later.
    #[serde(rename = "MessagingActivationUsingPhoneNumber")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub messaging_activation_using_phone_number: Option<String>,
    /// The key to skip the on-boarding informational screens for user education (Go Home, Cover Sheet, Multitasking & Control Center, for example) in iOS. This key is available in iOS 11 and later, and deprecated in iOS 14.
    #[serde(rename = "OnBoarding")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub on_boarding: Option<String>,
    /// The key to hide and disable the passcode pane. This key is available in iOS 7 and later.
    #[serde(rename = "Passcode")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub passcode: Option<String>,
    /// The key to skip Apple Pay setup. This key is available in iOS 8.1 and later, and macOS 10.12.4 and later.
    #[serde(rename = "Payment")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub payment: Option<String>,
    /// The key to skip the privacy pane. This key is available in iOS 11.13 and later, tvOS 11.13 and later, and macOS 10.13.4 and later.
    #[serde(rename = "Privacy")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub privacy: Option<String>,
    /// The key to disable restoring from backup. This key is available in iOS 7 and later, and macOS 10.9 and later.
    #[serde(rename = "Restore")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub restore: Option<String>,
    /// The key to skip the Restore Completed pane. This key is available in iOS 14 and later.
    #[serde(rename = "RestoreCompleted")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub restore_completed: Option<String>,
    /// The key to skip the tvOS screen about using aerial screensavers in ATV. This key is available in tvOS 10.2 and later.
    #[serde(rename = "ScreenSaver")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub screen_saver: Option<String>,
    /// The key to skip the Safety pane. This key is available in iOS 16 and later.
    #[serde(rename = "Safety")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub safety: Option<String>,
    /// The key to skip the Screen Time pane. This key is available in iOS 12 and later, and macOS 10.15 and later.
    #[serde(rename = "ScreenTime")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub screen_time: Option<String>,
    /// The key to skip the add cellular plan pane. This key is available in iOS 12 and later.
    #[serde(rename = "SIMSetup")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub sim_setup: Option<String>,
    /// The key to disable Siri. This key is available in iOS 7 and later, tvOS 10.2 and later, and macOS 10.12 and later.
    #[serde(rename = "Siri")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub siri: Option<String>,
    /// The key to skip the mandatory software update screen in iOS. This key is available in iOS 12 and later.
    #[serde(rename = "SoftwareUpdate")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub software_update: Option<String>,
    /// The key to skip the Dictation pane. This pane isn't always skippable because it appears before the device retrieves the Cloud Configuration from the server. This key is available in iOS 13 and later.
    #[serde(rename = "SpokenLanguage")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub spoken_language: Option<String>,
    /// The key to skip the Tap To Set Up option in Apple TV related to using an iOS device to set up your Apple TV. This key is available in tvOS 10.2 and later.
    #[serde(rename = "TapToSetup")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tap_to_setup: Option<String>,
    /// The key to skip the Terms of Address pane. This key isn't always skippable because this pane appears before the device retrieves the Cloud Configuration from the server. This key is available in iOS 16 and later, and macOS 13 and later.
    #[serde(rename = "TermsOfAddress")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub terms_of_address: Option<String>,
    /// The key to skip Terms and Conditions. This key is available in iOS 7 and later, tvOS 10.2 and later, and macOS 10.9 and later.
    #[serde(rename = "TOS")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tos: Option<String>,
    /// The key to skip TV home screen layout sync screen. This key is available in tvOS 11 and later.
    #[serde(rename = "TVHomeScreenSync")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tv_home_screen_sync: Option<String>,
    /// The key to skip the TV provider sign in screen. This key is available in tvOS 11 and later.
    #[serde(rename = "TVProviderSignIn")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tv_provider_sign_in: Option<String>,
    /// The key to skip the “Where is this Apple TV?” screen in tvOS. This key is available in tvOS 11.4 and later.
    #[serde(rename = "TVRoom")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tv_room: Option<String>,
    /// The key to skip the Software Update Complete pane. This key is available in iOS 14 and later.
    #[serde(rename = "UpdateCompleted")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub update_completed: Option<String>,
    /// The key to skip Wallpaper setup.
    /// This key is available in macOS 14.1 and later,
    #[serde(rename = "Wallpaper")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub wallpaper: Option<String>,
    /// The key to skip the screen for watch migration. This key is available in iOS 11 and later.
    #[serde(rename = "WatchMigration")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub watch_migration: Option<String>,
    /// If the key is included in the SkipSetup array the Web Content Filtering pane will be skipped.
    #[serde(rename = "WebContentFiltering")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub web_content_filtering: Option<String>,
    /// The key to skip the Get Started pane. This key is available in iOS 13 and later and macOS 15 and later.
    #[serde(rename = "Welcome")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub welcome: Option<String>,
    /// The key to skip zoom setup. This key is available in iOS 8.3 and later, and deprecated in iOS 17.
    #[serde(rename = "Zoom")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub zoom: Option<String>,
}

/// The JSON object returned from the MDM server's Enrollment SSO endpoint.
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct EnrollmentSSODocument {
    /// The iTunes Store ID of the app to download prior to enrollment, to support Enrollment SSO during enrollment. Using developer mode ignores this key.
    #[serde(rename = "iTunesStoreID")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub i_tunes_store_id: Option<serde_yaml::Value>,
    /// An array of App IDs that specify apps that Enrollment SSO developer mode can use. In Enrollment SSO documents delivered through the developer endpoint, this key must be present and contain at least one value. In Enrollment SSO documents delivered by the standard Enrollment SSO endpoint, this key must not be present.
    #[serde(rename = "AppIDs")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub app_i_ds: Option<serde_yaml::Value>,
    /// An array of associated domains that the device uses with the Enrollment SSO extension.
    #[serde(rename = "AssociatedDomains")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub associated_domains: Option<serde_yaml::Value>,
    /// If 'true,' allows the domain to directly verify site association, instead of at Apple's servers. Use this verification only with domains that are inaccessible on the public Internet.
    #[serde(rename = "AssociatedDomainsEnableDirectDownloads")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub associated_domains_enable_direct_downloads: Option<bool>,
    /// The profile containing an ExtensibleSingleSignOn payload that specifies the SSO extension in the downloaded app prior to enrollment. This profile may contain certificate payloads.
    #[serde(rename = "ConfigurationProfile")]
    pub configuration_profile: serde_yaml::Value,
}

/// The passwordHash object used in the AccountConfiguration and SetAutoAdminPassword commands
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct PasswordHash {
    /// A dictionary containing the entropy, iterations and salt
    #[serde(rename = "SALTED-SHA512-PBKDF2")]
    pub salted_sha512_pbkdf2: serde_yaml::Value,
}

/// The definition of MachineInfo payload sent by a client when fetching an MDM enrollment profile
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct MachineInfo {
    /// The device's UDID.
    #[serde(rename = "UDID")]
    pub udid: String,
    /// The device's serial number.
    #[serde(rename = "SERIAL")]
    pub serial: String,
    /// The device's product type, e.g. iPhone5,1.
    #[serde(rename = "PRODUCT")]
    pub product: String,
    /// The build version installed on the device, e.g. 7A182.
    #[serde(rename = "VERSION")]
    pub version: String,
    /// The OS version installed on the device, e.g. 17.0.
    #[serde(rename = "OS_VERSION")]
    pub os_version: String,
    /// The device's operating system supplemental build version (if available).
    #[serde(rename = "SUPPLEMENTAL_BUILD_VERSION")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub supplemental_build_version: Option<String>,
    /// The device's operating system supplemental OS version extra (if available).
    #[serde(rename = "SUPPLEMENTAL_OS_VERSION_EXTRA")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub supplemental_os_version_extra: Option<String>,
    /// The device's IMEI (if available).
    #[serde(rename = "IMEI")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub imei: Option<String>,
    /// The device's MEID (if available).
    #[serde(rename = "MEID")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub meid: Option<String>,
    /// The user's currently-selected language, e.g. en.
    #[serde(rename = "LANGUAGE")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub language: Option<String>,
    /// If set to "true", indicates that the device can be triggered by the server to do a required software update.
    #[serde(rename = "MDM_CAN_REQUEST_SOFTWARE_UPDATE")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub mdm_can_request_software_update: Option<bool>,
    /// The pairing token to validate when a watch is enrolling.
    #[serde(rename = "PAIRING_TOKEN")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub pairing_token: Option<serde_yaml::Value>,
    /// The device model identifier used to lookup available OS updates through https://gdmf.apple.com/v2/pmv.
    #[serde(rename = "SOFTWARE_UPDATE_DEVICE_ID")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub software_update_device_id: Option<String>,
}

