name = "mattrax"
pages_build_output_dir = "dist"
compatibility_date = "2024-05-12"
compatibility_flags = ["nodejs_compat"]

[[durable_objects.bindings]]
name = "ORG_REALTIME_DO"
class_name = "OrgRealtime"
script_name = "./src/api/rest/cloud/OrgRealtime.ts"

# TODO: https://github.com/mattrax/Mattrax/actions/runs/9312961397/job/25634645798
# [[migrations]]
# tag = "v1"
# new_classes = ["OrgRealtime"]
