[package]
name = "mattrax-policy"
version = "0.0.1"
edition = "2021"

[dependencies]
serde = { version = "1.0.197", features = ["derive"] }
specta = { version = "=2.0.0-rc.7", features = ["typescript"] }
