[package]
name = "mx-utils"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
hex = "0.4.3"
serde = { workspace = true }
tracing-appender = "0.2.3"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
