[workspace]
resolver = "2"
members = ["apps/mattrax", "crates/*"]

[workspace.dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread", "net", "signal"] }
serde = { version = "1", features = ["derive", "rc"] }
axum = { version = "0.8" }
serde_json = { version = "1" }
tracing = { version = "0.1" }
sqlx = { version = "0.8", default-features = false, features = ["mysql", "runtime-tokio", "tls-rustls", "derive", "macros", "migrate", "json", "chrono"] }
uuid = { version = "1", features = ["serde"] }
cryptographic-message-syntax = { version = "0.27.0", default-features = false, features = ["http"] } # TODO: Why do we need `reqwest` for `SignedDataBuilder`. Remove `http` feature plz!
x509-verify = { version = "0.4.6", features = ["pem", "sha1", "std", "x509"] }
thiserror = "2"
reqwest = { version = "0.12.12", default-features = false, features = ["rustls-tls", "charset", "http2", "macos-system-configuration", "json"] }
chrono = { version = "0.4.39", features = ["serde"] }
zeroize = "1.8.1"

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
cargo = { level = "warn", priority = -1 }
unwrap_used = { level = "warn", priority = -1 }
panic = { level = "warn", priority = -1 }
todo = { level = "warn", priority = -1 }
panic_in_result_fn = { level = "warn", priority = -1 }

# Makes a massive difference to RSA key generation in development
[profile.dev.package.num-bigint-dig]
opt-level = 3
