[workspace]
resolver = "2"
members = ["apps/mattrax", "crates/*"]

[workspace.dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread", "net", "signal"] }
serde = { version = "1", features = ["derive", "rc"] }
axum = { version = "0.7" }
serde_json = { version = "1" }
tracing = { version = "0.1" }

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
cargo = { level = "warn", priority = -1 }
unwrap_used = { level = "warn", priority = -1 }
panic = { level = "warn", priority = -1 }
todo = { level = "warn", priority = -1 }
panic_in_result_fn = { level = "warn", priority = -1 }
