//! This file is generated by the 'export' unit test in 'mttx-policy'! Do not modify it manually!

/**
 * TODO
 */
export type Policy = {
	id: string;
	name: string;
	description?: string | null;
	configuration?: Configuration[];
};

/**
 * TODO
 */
export type Configuration =
	/**
	 * TODO
	 */
	| { CustomWindows: { oma_uri: string; data: string } }
	/**
	 * TODO
	 */
	| { CustomMacOS: { path: string } };
