[package]
name = "mx-crypto"
version = "0.0.0"
edition = "2021"
publish = false

[lints]
workspace = true

# TODO: `zeroize` feature to enable it on deps easily

# TODO: Prune dependencies + drop `openssl` & `mx-golang
[dependencies]
mx-golang = { version = "0.0.0", path = "../mx-golang" }
openssl = { version = "0.10.68", features = ["vendored"] } # TODO: Don't set `vendored` if we publish this library

cryptographic-message-syntax = { version = "0.27.0", default-features = false, features = ["http"] } # TODO: Why do we need `reqwest` for `SignedDataBuilder`. Remove `http` feature plz!
aes = "0.9.0-pre.2"
asn1 = "0.20.0"
cbc = "0.2.0-pre.2"
des = "0.9.0-pre.2"
rand = "0.8.5" # TODO: Remove this and make user parse it?
bytes = "1.9.0"
bcder = "0.7.4"
x509-certificate = "0.24.0"
chrono.workspace = true
rsa = "0.9.7"
bitflags = "2.6.0"
bitvec = "1.0.1"
yasna = "0.5.2"
thiserror.workspace = true
x509-verify = { version = "0.4.6", features = ["pem", "sha1", "std", "x509"] }
sha1 = "0.10.6"

# rasn = { version = "0.22.2", features = ["std"] }
# rasn-cms = "0.22.2"
