[package]
name = "ingest"
description = "An internal tool for automatically scaffolding types from external schemas."
version = "0.0.0"
edition = "2021"
publish = false

[lints]
workspace = true

[dependencies]
Inflector = "0.11.4"
schemars = { version = "0.8.21", default-features = false }
serde_yaml = "0.9.34"
