[package]
name = "ingest"
description = "An internal tool for automatically scaffolding types from external schemas."
version = "0.0.0"
edition = "2021"
publish = false

[lints]
workspace = true

[dependencies]
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
specta-jsonschema.workspace = true
specta-rust.workspace = true
Inflector = "0.11.4"
prettyplease = "0.2.29"
regex = "1.11.1"
schemars = { version = "0.8.21", default-features = false }
serde_yaml = "0.9.34"
serde_yaml2 = "0.1.2"
serde_yml = "0.0.12"
specta = "=2.0.0-rc.22"
typify = "0.3.0"
yaml-rust2 = "0.9.0"
