[package]
name = "mx-api"
version = "0.0.0"
edition = "2021"
publish = false

[lints]
workspace = true

[dependencies]
mx-apple = { path = "../mx-apple" }
mx-windows = { path = "../mx-windows" }
axum.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
reqwest.workspace = true
chrono.workspace = true
sqlx.workspace = true
tokio.workspace = true
zeroize.workspace = true
x509-certificate = "0.24.0"
chacha20poly1305 = "0.10.1"
jsonwebtoken = "9.3.0"
