[package]
name = "mx-api"
version = "0.0.0"
edition = "2021"
publish = false

[lints]
workspace = true

[dependencies]
mx-core = { path = "../mx-core" }
mx-apple = { path = "../mx-apple" }
mx-windows = { path = "../mx-windows" }
axum.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
reqwest = "0.12.12"
