[package]
name = "mx-conflict"
version = "0.0.1"
edition = "2021"
publish = false

[dependencies]
mx-dmvalue = { path = "../dmvalue" }

serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.115"

[dev-dependencies]
pretty_assertions = "1.4.0"
