/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const IconIcRoundCheck: typeof import('~icons/ic/round-check.jsx')['default']
  const IconLogosAndroidIcon: typeof import('~icons/logos/android-icon.jsx')['default']
  const IconLogosIos: typeof import('~icons/logos/ios.jsx')['default']
  const IconLogosLinuxTux: typeof import('~icons/logos/linux-tux.jsx')['default']
  const IconLogosMacos: typeof import('~icons/logos/macos.jsx')['default']
  const IconLogosMicrosoftWindowsIcon: typeof import('~icons/logos/microsoft-windows-icon.jsx')['default']
  const IconMdiSlashForward: typeof import('~icons/mdi/slash-forward.jsx')['default']
  const IconPhAppWindow: typeof import('~icons/ph/app-window.jsx')['default']
  const IconPhArrowsVerticalBold: typeof import('~icons/ph/arrows-vertical-bold.jsx')['default']
  const IconPhCaretUpDown: typeof import('~icons/ph/caret-up-down.jsx')['default']
  const IconPhCheck: typeof import('~icons/ph/check.jsx')['default']
  const IconPhCheckBold: typeof import('~icons/ph/check-bold.jsx')['default']
  const IconPhCheckCircleDuotone: typeof import('~icons/ph/check-circle-duotone.jsx')['default']
  const IconPhDevices: typeof import('~icons/ph/devices.jsx')['default']
  const IconPhDotsThreeBold: typeof import('~icons/ph/dots-three-bold.jsx')['default']
  const IconPhLaptop: typeof import('~icons/ph/laptop.jsx')['default']
  const IconPhMagnifyingGlassLight: typeof import('~icons/ph/magnifying-glass-light.jsx')['default']
  const IconPhPlusCircle: typeof import('~icons/ph/plus-circle.jsx')['default']
  const IconPhPuzzlePiece: typeof import('~icons/ph/puzzle-piece.jsx')['default']
  const IconPhScroll: typeof import('~icons/ph/scroll.jsx')['default']
  const IconPhSelection: typeof import('~icons/ph/selection.jsx')['default']
  const IconPhUser: typeof import('~icons/ph/user.jsx')['default']
  const IconPhWarningCircleDuotone: typeof import('~icons/ph/warning-circle-duotone.jsx')['default']
  const IconPhXBold: typeof import('~icons/ph/x-bold.jsx')['default']
  const IconSvgSpinners90Ring: typeof import('~icons/svg-spinners/90-ring.jsx')['default']
  const IconTablerCheck: typeof import('~icons/tabler/check.jsx')['default']
  const IconTablerChevronDown: typeof import('~icons/tabler/chevron-down.jsx')['default']
  const IconTablerChevronLeft: typeof import('~icons/tabler/chevron-left.jsx')['default']
  const IconTablerChevronRight: typeof import('~icons/tabler/chevron-right.jsx')['default']
  const IconTablerChevronUp: typeof import('~icons/tabler/chevron-up.jsx')['default']
  const IconTablerCircle: typeof import('~icons/tabler/circle.jsx')['default']
  const IconTablerDots: typeof import('~icons/tabler/dots.jsx')['default']
  const IconTablerSelector: typeof import('~icons/tabler/selector.jsx')['default']
  const IconTablerX: typeof import('~icons/tabler/x.jsx')['default']
}
