/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const IconCarbonCaretDown: typeof import('~icons/carbon/caret-down.jsx')['default']
  const IconCarbonCaretSort: typeof import('~icons/carbon/caret-sort.jsx')['default']
  const IconLogosGoogleIcon: typeof import('~icons/logos/google-icon.jsx')['default']
  const IconLogosMicrosoftAzure: typeof import('~icons/logos/microsoft-azure.jsx')['default']
  const IconPhAppDuotone: typeof import('~icons/ph/app-duotone.jsx')['default']
  const IconPhAppWindowDuotone: typeof import('~icons/ph/app-window-duotone.jsx')['default']
  const IconPhArrow: typeof import('~icons/ph/arrow.jsx')['default']
  const IconPhArrowDown: typeof import('~icons/ph/arrow-down.jsx')['default']
  const IconPhArrowDownBold: typeof import('~icons/ph/arrow-down-bold.jsx')['default']
  const IconPhBookDuotone: typeof import('~icons/ph/book-duotone.jsx')['default']
  const IconPhBoundingBoxDuotone: typeof import('~icons/ph/bounding-box-duotone.jsx')['default']
  const IconPhClipboardDuotone: typeof import('~icons/ph/clipboard-duotone.jsx')['default']
  const IconPhCogDuotone: typeof import('~icons/ph/cog-duotone.jsx')['default']
  const IconPhGearDuotone: typeof import('~icons/ph/gear-duotone.jsx')['default']
  const IconPhHouseDuotone: typeof import('~icons/ph/house-duotone.jsx')['default']
  const IconPhHouseLight: typeof import('~icons/ph/house-light.jsx')['default']
  const IconPhLaptopDuotone: typeof import('~icons/ph/laptop-duotone.jsx')['default']
  const IconPhPhoneDuotone: typeof import('~icons/ph/phone-duotone.jsx')['default']
  const IconPhUserDuotone: typeof import('~icons/ph/user-duotone.jsx')['default']
}
