[package]
name = "apple-pfm"
description = "Parser for Apple's Preference Manifest Files"
version = "0.0.0"
edition = "2021"
publish = false

[lints]
workspace = true

[dependencies]
plist.workspace = true
serde.workspace = true
thiserror.workspace = true

[dev-dependencies]
pretty_assertions = "1.4.1"
