AWSTemplateFormatVersion: 2010-09-09

Outputs:
  VercelAccessKeyId:
    Description: AWS_ACCESS_KEY_ID
    Value: !Ref VercelAccessKey

  VercelAccessKeySecret:
    Description: AWS_SECRET_ACCESS_KEY
    Value: !GetAtt VercelAccessKey.SecretAccessKey

Resources:
  ForgeData:
    Type: AWS::S3::Bucket

  VercelUser:
    Type: AWS::IAM::User
    Properties:
      Policies:
        - PolicyName: S3
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                Resource: !Sub arn:aws:s3:::${ForgeData}/*
        
        - PolicyName: SES
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - ses:SendEmail
                Resource: "*" # TODO: Props restrict this down to the correct domain
                # TODO: Restrict `ses:FromAddress` and `ses:FromDisplayName` for better security

  VercelAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName:
        !Ref VercelUser
  
  # Intune doesn't have a "subscribe to devices" endpoint so we abuse it's email callback feature.

  IntuneCallbackReceiptRuleSet:
    Type: 'AWS::SES::ReceiptRuleSet'

  IntuneCallbackQueue:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
        - Protocol: https
          Endpoint: !Join ["https://sns:", [ !Ref VercelAccessKey, "@mattrax-forge.vercel.app/api/webhook/sns" ] ]
        - Protocol: https
          Endpoint: https://webhook.site/6fe25dc3-4a2c-4559-a221-772156ca5971 # TODO: Correct this URL

  IntuneCallbackReceiptRule:
    Type: AWS::SES::ReceiptRule
    Properties:
      RuleSetName: bridge-to-sns
      Rule:
        Enabled: true
        ScanEnabled: false
        TlsPolicy: Require
        Recipients:
         - intune-alerts@mattrax.app
        Actions:
         - SNSAction:
            Encoding: UTF-8
            TopicArn: !Ref IntuneCallbackQueue

