[env]
# Default used by `cargo run` and Rust Analyzer
DATABASE_URL="mysql://root:@localhost:3306/mattrax"
SECRET = "1a5e7ce917928fec5e5642f3493f10979a97225c23f2102f2d9edfbf035b9fbe"
LICENCE = "self-hosting-is-not-currently-supported"

# TODO: it's annoying we can just use the `DATABASE_URL` from above in these.
# This also means if you override `DATABASE_URL` it won't be used here unlike for `cargo run`.
[alias]
migrate = "sqlx migrate run --source crates/mx-api/migrations --database-url mysql://root:@localhost:3306/mattrax"
resetdb = "sqlx database reset --source crates/mx-api/migrations --database-url mysql://root:@localhost:3306/mattrax"

gen-apple = "run -p apple-dm-schema --bin gen-apple"
gen-apple-schema = "run -p apple-dm-schema --bin gen-apple-schema"
