[package]
name = "mx-apple"
version = "0.0.0"
edition = "2021"
publish = false

[lints]
workspace = true

[dependencies]
serde.workspace = true
uuid.workspace = true
cryptographic-message-syntax.workspace = true
thiserror.workspace = true
plist = "1.7.0"
x509-verify.workspace = true
rsa = { version = "0.9.7", features = ["sha1"] }
sha1 = { version = "0.10.6", features = ["oid"] }
x509-certificate = "0.24.0"
