[package]
name = "specta-zod"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
specta = { workspace = true, features = ["typescript"] }
thiserror = "1.0.58"
