/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const IconCarbonCaretDown: typeof import('~icons/carbon/caret-down.jsx')['default']
  const IconCarbonCaretSort: typeof import('~icons/carbon/caret-sort.jsx')['default']
  const IconClarityEyeHideLine: typeof import('~icons/clarity/eye-hide-line.jsx')['default']
  const IconClarityEyeShowLine: typeof import('~icons/clarity/eye-show-line.jsx')['default']
  const IconIcOutlineClose: typeof import('~icons/ic/outline-close.jsx')['default']
  const IconIcRoundCheck: typeof import('~icons/ic/round-check.jsx')['default']
  const IconLogosGoogleIcon: typeof import('~icons/logos/google-icon.jsx')['default']
  const IconLogosMicrosoftAzure: typeof import('~icons/logos/microsoft-azure.jsx')['default']
  const IconPhAppWindowDuotone: typeof import('~icons/ph/app-window-duotone.jsx')['default']
  const IconPhArrowDownBold: typeof import('~icons/ph/arrow-down-bold.jsx')['default']
  const IconPhBoundingBoxDuotone: typeof import('~icons/ph/bounding-box-duotone.jsx')['default']
  const IconPhClipboardDuotone: typeof import('~icons/ph/clipboard-duotone.jsx')['default']
  const IconPhGearDuotone: typeof import('~icons/ph/gear-duotone.jsx')['default']
  const IconPhHouseDuotone: typeof import('~icons/ph/house-duotone.jsx')['default']
  const IconPhLaptopDuotone: typeof import('~icons/ph/laptop-duotone.jsx')['default']
  const IconPhUserDuotone: typeof import('~icons/ph/user-duotone.jsx')['default']
  const IconPrimeExternalLink: typeof import('~icons/prime/external-link.jsx')['default']
}
