/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const IconCarbonCaretDown: typeof import('~icons/carbon/caret-down.jsx')['default']
  const IconCarbonCaretSort: typeof import('~icons/carbon/caret-sort.jsx')['default']
  const IconClarityEyeHideLine: typeof import('~icons/clarity/eye-hide-line.jsx')['default']
  const IconClarityEyeShowLine: typeof import('~icons/clarity/eye-show-line.jsx')['default']
  const IconIcOutlineClose: typeof import('~icons/ic/outline-close.jsx')['default']
  const IconIcRoundCheck: typeof import('~icons/ic/round-check.jsx')['default']
  const IconLogosChrome: typeof import('~icons/logos/chrome.jsx')['default']
  const IconLogosGoogleIcon: typeof import('~icons/logos/google-icon.jsx')['default']
  const IconLogosMicrosoftAzure: typeof import('~icons/logos/microsoft-azure.jsx')['default']
  const IconLogosMicrosoftIcon: typeof import('~icons/logos/microsoft-icon.jsx')['default']
  const IconLogosSlackIcon: typeof import('~icons/logos/slack-icon.jsx')['default']
  const IconPhAppDuotone: typeof import("~icons/ph/app-duotone.jsx")["default"]
  const IconPhAppWindowDuotone: typeof import('~icons/ph/app-window-duotone.jsx')['default']
  const IconPhArrow: typeof import("~icons/ph/arrow.jsx")["default"]
  const IconPhArrowDown: typeof import("~icons/ph/arrow-down.jsx")["default"]
  const IconPhArrowDownBold: typeof import('~icons/ph/arrow-down-bold.jsx')['default']
  const IconPhBookDuotone: typeof import('~icons/ph/book-duotone.jsx')['default']
  const IconPhBoundingBoxDuotone: typeof import('~icons/ph/bounding-box-duotone.jsx')['default']
  const IconPhClipboardDuotone: typeof import('~icons/ph/clipboard-duotone.jsx')['default']
  const IconPhCogDuotone: typeof import('~icons/ph/cog-duotone.jsx')['default']
  const IconPhCookingPotDuotone: typeof import('~icons/ph/cooking-pot-duotone.jsx')['default']
  const IconPhGearDuotone: typeof import('~icons/ph/gear-duotone.jsx')['default']
  const IconPhHouseDuotone: typeof import('~icons/ph/house-duotone.jsx')['default']
  const IconPhHouseLight: typeof import("~icons/ph/house-light.jsx")["default"]
  const IconPhLaptopDuotone: typeof import('~icons/ph/laptop-duotone.jsx')['default']
  const IconPhLockDuotone: typeof import('~icons/ph/lock-duotone.jsx')['default']
  const IconPhPhoneDuotone: typeof import("~icons/ph/phone-duotone.jsx")["default"]
  const IconPhPlusCircleBold: typeof import('~icons/ph/plus-circle-bold.jsx')['default']
  const IconPhPlusCircleDuotone: typeof import('~icons/ph/plus-circle-duotone.jsx')['default']
  const IconPhUserDuotone: typeof import('~icons/ph/user-duotone.jsx')['default']
}
