import {
	Card,
	CardTitle,
	Checkbox,
	NumberField,
	NumberFieldDecrementTrigger,
	NumberFieldIncrementTrigger,
	NumberFieldInput,
	Select,
	SelectContent,
	SelectItem,
	SelectTrigger,
	SelectValue,
} from "@mattrax/ui";
import { Match, createMemo, Switch, Show } from "solid-js";
import { For } from "solid-js";
import { createStore } from "solid-js/store";

import windowsConfig from "../../../../../../../../ingest/generated/dff.json";
import { WindowsDDFPolicy } from "../../../../../../../../ingest/generated/dff";

// can be generated by specta

// can be codegened to match the specta types
//
// if codegen is done in rust we can reuse the specta structs and convert them to json
const config = {
	windows: windowsConfig as any,
} as { windows: Record<string, WindowsDDFPolicy> };

export function createVisualEditor() {
	const [selected, setSelected] = createStore<{
		[K in keyof typeof config.windows]?: { enabled: boolean; data: any };
	}>({});

	return { selected, setSelected };
}

export type VisualEditorController = ReturnType<typeof createVisualEditor>;

export function VisualEditor(props: { controller: VisualEditorController }) {
	return (
		<div class="w-full h-full flex flex-row gap-4">
			<ul class="flex-1 gap-4 flex flex-col">
				<For
					each={Object.entries(props.controller.selected).filter(
						([_, v]) => v?.enabled,
					)}
				>
					{([key, value]) => {
						const itemConfig = () =>
							config.windows[key as keyof typeof config.windows];

						const when = () => {
							const c = itemConfig();
							if (c && value) return { itemConfig: c, value };
						};

						return (
							<Show when={when()} keyed>
								{({ itemConfig, value }) => (
									<div>
										<Card class="p-4 space-y-4">
											<CardTitle>{(config.windows as any)[key].name}</CardTitle>
											<Switch fallback="bruh">
												<Match
													when={itemConfig.format === "int" && itemConfig}
													keyed
												>
													{(itemConfig) => (
														<Switch
															fallback={() => {
																console.log(itemConfig);
																return <>lmao</>;
															}}
														>
															<Match
																when={
																	itemConfig.allowedValues &&
																	itemConfig.allowedValues.valueType ===
																		"enum" &&
																	itemConfig.allowedValues
																}
															>
																{(allowedValues) => {
																	const options = createMemo(() =>
																		Object.entries(allowedValues().enum).map(
																			([value, config]) => ({
																				...config,
																				value,
																			}),
																		),
																	);

																	const selectValue = createMemo(() =>
																		options().find(
																			(o) =>
																				o.value ===
																				(value.data ?? itemConfig.defaultValue),
																		),
																	);

																	type Option = ReturnType<
																		typeof options
																	>[number];

																	return (
																		<Select<Option>
																			options={options()}
																			multiple={false}
																			defaultValue={options().find(
																				(o) =>
																					o.value ===
																					itemConfig.defaultValue.toString(),
																			)}
																			optionValue="value"
																			optionTextValue="description"
																			optionDisabled={() => false}
																			itemComponent={(props) => (
																				<SelectItem item={props.item}>
																					{props.item.rawValue.description}
																				</SelectItem>
																			)}
																			value={selectValue()}
																			onChange={(option) => {
																				console.log(option);
																				props.controller.setSelected(
																					key as any,
																					{
																						data: option.value,
																					},
																				);
																			}}
																		>
																			<SelectTrigger>
																				<SelectValue<Option>>
																					{(state) => (
																						<>
																							{
																								state.selectedOption()
																									.description
																							}
																						</>
																					)}
																				</SelectValue>
																			</SelectTrigger>
																			<SelectContent />
																		</Select>
																	);
																}}
															</Match>
															<Match
																when={
																	itemConfig.allowedValues &&
																	itemConfig.allowedValues.valueType ===
																		"range" &&
																	itemConfig.allowedValues
																}
															>
																{(allowedValues) => {
																	return (
																		<NumberField
																			minValue={allowedValues().min}
																			maxValue={allowedValues().max}
																			defaultValue={itemConfig.defaultValue}
																			value={
																				value.data ?? itemConfig.defaultValue
																			}
																			onChange={(value) =>
																				props.controller.setSelected(
																					key as any,
																					{
																						data: value,
																					},
																				)
																			}
																		>
																			<div class="relative">
																				<NumberFieldInput />
																				<NumberFieldIncrementTrigger />
																				<NumberFieldDecrementTrigger />
																			</div>
																		</NumberField>
																	);
																}}
															</Match>
														</Switch>
													)}
												</Match>
											</Switch>
										</Card>
									</div>
								)}
							</Show>
						);
					}}
				</For>
			</ul>
			<ul class="flex-1 overflow-hidden">
				<For each={Object.entries(config.windows)}>
					{([key, value]) => (
						<li class="flex flex-row p-2 items-center gap-4">
							<Checkbox
								onChange={(value) => {
									if (value)
										props.controller.setSelected(key as any, {
											enabled: value,
										});
								}}
							/>
							<div class="overflow-hidden">
								<span class="font-medium">{value.name}</span>
								<p class="text-sm text-neutral-500 overflow-y-auto scrollbar-none">
									{key}
								</p>
							</div>
						</li>
					)}
				</For>
			</ul>
		</div>
	);
}
