pub struct SettingsCommand {}
pub struct ClearActivationLockBypassCodeCommand {}
pub struct RequestUnlockTokenCommand {}
pub struct SetRecoveryLockCommand {}
pub struct InstallEnterpriseApplicationCommand {}
pub struct RefreshCellularPlansCommand {}
pub struct RemoveProfileCommand {}
pub struct UserConfiguredCommand {}
pub struct LomDeviceRequestCommand {}
pub struct ManagedMediaListCommand {}
pub struct InstallProvisioningProfileCommand {}
pub struct CertificateListCommand {}
pub struct DeclarativeManagementCommand {}
pub struct RestartDeviceCommand {}
pub struct DeviceLocationCommand {}
pub struct ValidateApplicationsCommand {}
pub struct EnableRemoteDesktopCommand {}
pub struct ProvisioningProfileListCommand {}
pub struct UnlockUserAccountCommand {}
pub struct RotateFileVaultKeyCommand {}
pub struct NsextensionMappingsCommand {}
pub struct InstalledApplicationListCommand {}
pub struct ShutDownDeviceCommand {}
pub struct DisableRemoteDesktopCommand {}
pub struct RestrictionsCommand {}
pub struct DeviceInformationCommand {}
pub struct ScheduleOSUpdateCommand {}
pub struct SetFirmwarePasswordCommand {}
pub struct PlayLostModeSoundCommand {}
pub struct RemoveProvisioningProfileCommand {}
pub struct AvailableOSUpdatesCommand {}
pub struct ActiveNSExtensionsCommand {}
pub struct ClearPasscodeCommand {}
pub struct VerifyFirmwarePasswordCommand {}
pub struct RequestMirroringCommand {}
pub struct LogOutUserCommand {}
pub struct ManagedApplicationFeedbackCommand {}
pub struct InstallProfileCommand {}
pub struct LomSetupRequestCommand {}
pub struct SetAutoAdminPasswordCommand {}
pub struct DeleteUserCommand {}
pub struct RemoveMediaCommand {}
pub struct AccountConfigurationCommand {}
pub struct VerifyRecoveryLockCommand {}
pub struct DisableLostModeCommand {}
pub struct DeviceConfiguredCommand {}
pub struct ApplyRedemptionCodeCommand {}
pub struct ScheduleOSUpdateScanCommand {}
pub struct InviteToProgramCommand {}
pub struct InstallApplicationCommand {}
pub struct OsUpdateStatusCommand {}
pub struct StopMirroringCommand {}
pub struct ContentCachingInformationCommand {}
pub struct UserListCommand {}
pub struct RemoveApplicationCommand {}
pub struct InstallMediaCommand {}
pub struct ManagedApplicationAttributesCommand {}
pub struct ClearRestrictionsPasswordCommand {}
pub struct ProfileListCommand {}
pub struct ActivationLockBypassCodeCommand {}
pub struct DeviceLockCommand {}
pub struct EnableLostModeCommand {}
pub struct ManagedApplicationConfigurationCommand {}
pub struct EraseDeviceCommand {}
pub struct SecurityInfoCommand {}
pub struct ManagedApplicationListCommand {}