pub struct JabberAccount {}
pub struct 8021XSecondEthernet {}
pub struct ProfileRemovalPassword {}
pub struct ShareKit {}
pub struct WiFiManagedSetting {}
pub struct 8021XSecondActiveEthernet {}
pub struct SystemLogging {}
pub struct MediaManagementAllowedMedum {}
pub struct Notification {}
pub struct GlobalPreference {}
pub struct Vpn {}
pub struct SystemExtension {}
pub struct Scep {}
pub struct GlobalHTTPProxy {}
pub struct Domain {}
pub struct ParentalControlsContentFilter {}
pub struct SystemPreference {}
pub struct SmartCard {}
pub struct SystemMigration {}
pub struct NetworkUsageRule {}
pub struct TimeServer {}
pub struct Accessibility {}
pub struct Declaration {}
pub struct NetworkProxyConfiguration {}
pub struct Identification {}
pub struct ExtensibleSingleSignOn {}
pub struct Screensaver {}
pub struct EnergySaver {}
pub struct DnsSetting {}
pub struct DirectoryService {}
pub struct FileProvider {}
pub struct FdeFileVaultOption {}
pub struct AimAccount {}
pub struct Dock {}
pub struct CertificateRoot {}
pub struct Relay {}
pub struct SetupAssistant {}
pub struct ConferenceRoomDisplay {}
pub struct CalDAV {}
pub struct EducationConfiguration {}
pub struct SystemPolicyControl {}
pub struct ScreensaverUser {}
pub struct SoftwareUpdate {}
pub struct AppToAppLayerVPNMapping {}
pub struct ManagedPreference {}
pub struct ContentCaching {}
pub struct AssociatedDomain {}
pub struct MediaManagementDiscBurning {}
pub struct 8021XGlobalEthernet {}
pub struct AcmeCertificate {}
pub struct Finder {}
pub struct Account {}
pub struct Desktop {}
pub struct CommonPayloadKey {}
pub struct Ldap {}
pub struct Firewall {}
pub struct IdentityPreference {}
pub struct AutonomousSingleAppMode {}
pub struct CertificateRevocation {}
pub struct LightsOutManagementLOM {}
pub struct PrivacyPreferencesPolicyControl {}
pub struct FdeFileVault {}
pub struct SystemPolicyManaged {}
pub struct CertificatePKCS12 {}
pub struct Mdm {}
pub struct CertificateTransparency {}
pub struct CertificatePreference {}
pub struct ExchangeActiveSync {}
pub struct SubscribedCalendar {}
pub struct AirPrint {}
pub struct GoogleAccount {}
pub struct WebClip {}
pub struct Xsan {}
pub struct 8021XFirstEthernet {}
pub struct Apn {}
pub struct CardDAV {}
pub struct WapiIdentityCertificate {}
pub struct ParentalControlsDictionary {}
pub struct DnsProxy {}
pub struct Passcode {}
pub struct ParentalControlsDashboardWidgetRestriction {}
pub struct TvRemote {}
pub struct SystemPolicyKernelExtension {}
pub struct AirPlaySecurity {}
pub struct FdeRecoveryKeyRedirection {}
pub struct Mail {}
pub struct SecurityPreference {}
pub struct AppLock {}
pub struct CellularPrivateNetwork {}
pub struct MacOSServerAccount {}
pub struct ExchangeWebService {}
pub struct 8021XThirdActiveEthernet {}
pub struct Restriction {}
pub struct AppLayerVPN {}
pub struct ServiceManagementManagedLoginItem {}
pub struct WebContentFilter {}
pub struct XsanPreference {}
pub struct AppStore {}
pub struct AirPlay {}
pub struct TopLevel {}
pub struct ExtensibleSingleSignOnKerbero {}
pub struct WiFi {}
pub struct Font {}
pub struct Cellular {}
pub struct 8021XThirdEthernet {}
pub struct ManagedMenuExtra {}
pub struct LoginWindowLoginItem {}
pub struct UserPreference {}
pub struct MobileAccount {}
pub struct 8021XFirstActiveEthernet {}
pub struct ActiveDirectoryCertificate {}
pub struct NsextensionManagement {}
pub struct SystemPolicyRule {}
pub struct LockScreenMessage {}
pub struct CertificatePKCS1 {}
pub struct ParentalControlsTimeLimit {}
pub struct LoginItemsManagedItem {}
pub struct ParentalControlDictationAndProfanity {}
pub struct FdeRecoveryKeyEscrow {}
pub struct Printing {}
pub struct LoginWindowScript {}
pub struct SingleSignOn {}
pub struct CertificatePEM {}
pub struct LoginWindow {}
pub struct ParentalControlsGameCenter {}
pub struct TimeMachine {}