//! scep: Implementation of Simple Certificate Enrolment Protocol (RFC 8894) in Rust.
//!
//! // TODO: Example
#![forbid(unsafe_code)]

// TODO: Error handling
// TODO: Cleanup the signed attributes parsing code
// TODO: Debug implementations
// TODO: Documentation on everything

// TODO: Remove this
impl Service for () {}

mod constants;
mod pki_message;
// mod fail_info;
mod message_type;
mod pki_status;
mod scep;
mod service;

pub use constants::*;
pub use message_type::MessageType;
pub use pki_message::PkiMessage;
pub use pki_status::PKIStatus;
pub use scep::Scep;
pub use service::Service;

// // SenderNonce is a random 16 byte number.
// // A sender must include the senderNonce in each transaction to a recipient.
// type SenderNonce []byte

// // The RecipientNonce MUST be copied from the SenderNonce
// // and included in the reply.
// type RecipientNonce []byte

// // The TransactionID is a text
// // string generated by the client when starting a transaction. The
// // client MUST generate a unique string as the transaction identifier,
// // which MUST be used for all PKI messages exchanged for a given
// // enrolment, encoded as a PrintableString.
// type TransactionID string

// // WithCACerts adds option CA certificates to the SCEP operations.
// // Note: This changes the verification behavior of PKCS#7 messages. If this
// // option is specified, only caCerts will be used as expected signers.
// func WithCACerts(caCerts []*x509.Certificate) Option {
// 	return func(c *config) {
// 		c.caCerts = caCerts
// 	}
// }

// // WithCertsSelector adds the certificates certsSelector option to the SCEP
// // operations.
// // This option is effective when used with NewCSRRequest function. In
// // this case, only certificates selected with the certsSelector will be used
// // as the PKCS#7 message recipients.
// func WithCertsSelector(selector CertsSelector) Option {
// 	return func(c *config) {
// 		c.certsSelector = selector
// 	}
// }
