[package]
name = "pkcs_7"
version = "0.0.0"
edition = "2021"
publish = false

[lints]
workspace = true

# TODO: `zeroize` feature to enable it on deps easily

[dependencies]
# cryptographic-message-syntax.workspace = true # TODO: Maybe remove this long term?
aes = "0.9.0-pre.2"
# asn1 = "0.20.0"
cbc = "0.2.0-pre.2"
des = "0.9.0-pre.2"
rand = "0.8.5" # TODO: Remove this and make user parse it.
bytes = "1.9.0"
bcder = "0.7.4"
x509-certificate = "0.24.0"
rasn = { version = "0.22.2", features = ["std"] }
rasn-cms = "0.22.2"
