[package]
name = "mx-conflict"
version = "0.0.1"
edition = "2021"
publish = false

[dependencies]
mx-policy = { path = "../mx-policy" }
serde = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
pretty_assertions = "1.4.0"
