#!/bin/bash
# I personally hate pre-commit hooks but we *NEED* consistency formatting to deal with merge conflicts.

# We don't use `pnpm format` because it's slower
# node_modules/.bin/biome format --write .
pnpm fix
