[package]
name = "apple-dm"
description = "Generated Apple Device Management types"
version = "0.0.0"
edition = "2021"
publish = false

[lints]
workspace = true

[dependencies]
mx-crypto = { version = "0.0.0", path = "../mx-crypto" }
plist.workspace = true
serde.workspace = true
serde_yaml.workspace = true
uuid.workspace = true
