[package]
name = "apple-dm"
description = "Generated Apple Device Management types"
version = "0.0.0"
edition = "2021"
publish = false

[lints]
workspace = true

[dependencies]
mx-crypto = { path = "../mx-crypto" }
bira = { path = "../bira" }
plist.workspace = true
serde.workspace = true
uuid.workspace = true
