//! This file is generated by the 'export' unit test in 'mx-policy'! Do not modify it manually!

/**
 * TODO
 */
export type Policy = {
	id: string;
	name: string;
	description?: string | null;
	configurations?: { [key in string]: Configuration };
};

/**
 * TODO
 */
export type AndroidConfiguration = never;

/**
 * TODO
 */
export type AppleConfiguration = never;

/**
 * TODO
 */
export type Configuration =
	/**
	 * Windows-specific configurations
	 */
	| ({ type: "windows" } & WindowsConfiguration)
	/**
	 * Apple-specific configurations
	 */
	| ({ type: "apple" } & AppleConfiguration)
	/**
	 * Android-specific configurations
	 */
	| ({ type: "android" } & AndroidConfiguration)
	/**
	 * Script to run via `mattraxd`
	 */
	| ({ type: "script" } & Script);

/**
 * TODO
 */
export type CustomConfiguration = { oma_uri: string; value: WindowsValue };

/**
 * TODO
 */
export type Platform =
	| "windows"
	| "macOS"
	| "iOS"
	| "iPadOS"
	| "tvOS"
	| "watchOS"
	| "linux"
	| "android"
	| "ChromeOS";

/**
 * TODO
 */
export type Script = {
	shell: Shell;
	supported?: Platform[];
	trigger?: Trigger;
	run: string;
};

/**
 * TODO
 */
export type Shell = "powershell" | "bash" | "zsh";

/**
 * TODO
 */
export type Trigger =
	/**
	 * Only run the script once. If you modify the script it will run again.
	 */
	| { type: "once" }
	/**
	 * Trigger anytime a user logs in
	 */
	| { type: "login" }
	/**
	 * Trigger anytime a user logs out
	 */
	| { type: "logout" }
	/**
	 * Trigger anytime a device starts up
	 */
	| { type: "startup" }
	/**
	 * Trigger anytime the network state changes
	 */
	| { type: "network_state_change" }
	/**
	 * Trigger after the device has been enrolled.
	 */
	| { type: "enrollment_complete" }
	/**
	 * Trigger every time the device talks with Mattrax.
	 */
	| { type: "checkin" };

/**
 * TODO
 */
export type WindowsConfiguration =
	| { homepages: string[] }
	| { allow_graphing_calculator: boolean }
	| { custom: CustomConfiguration[] };

/**
 * TODO
 */
export type WindowsValue = string | number | string | boolean;
