//! This file is generated by the 'export' unit test in 'mattrax-policy'! Do not modify it manually!

/**
 * TODO
 */
export type Policy = {
	id: string;
	name: string;
	description?: string | null;
	configurations?: Configuration[];
};

/**
 * TODO
 */
export type Configuration =
	/**
	 * TODO
	 */
	| { type: "windows_custom"; oma_uri: string; value: string }
	/**
	 * TODO
	 */
	| { type: "apple_custom"; path: string };
