name: cd-deploy

on:
  workflow_call:
    inputs:
      project:
        type: string
        required: true

jobs:
  build:
    name: Build ${{ inputs.project }}
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.project }}
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Install
        run: pnpm i
      
      - name: Build
        env:
          NITRO_PRESET: cloudflare_pages
        run: pnpm landing build # TODO: Project name
  
  deploy:
    name: Deploy ${{ inputs.project}}
    runs-on: ubuntu-latest
    needs:
      - sst
      - build
    environment:
      name: ${{ inputs.project }}
      url: ${{ steps.result.outputs.DEPLOYMENT_URL }}
    steps:
      # We pull this so Cloudflare can link the commit up
      - name: Git clone the repository
        uses: actions/checkout@v4

      # TODO: Get built artifacts

      - name: Export `DEPLOYMENT_URL`
        id: result
        run: echo "DEPLOYMENT_URL=https://example.com" >> $GITHUB_OUTPUT
