name: Testing

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  merge_group:

jobs:
  testing:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: docker://ghcr.io/microsoftgraph/msgraph-cli:latest
        with:
          args: --version
