name: Vercel Email

on:
  push:
    branches: [main]
    paths:
      - "apps/email/**"
  workflow_dispatch:

jobs:
  deploy:
    name: "Deploy"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Install dependencies
        run: pnpm i

      - name: Deploy to Vercel
        run: npx vercel --token ${VERCEL_TOKEN} --prod
        working-directory: ./apps/email
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: prj_bxxgLnEGQNRkURcgnMmDOXNtKjSA
          VERCEL_ORG_ID: St9DAPMLqW2wVV3u9XxhUcE1
