[package]
name = "mattrax"
version = "0.0.0"
edition = "2021"
publish = false
default-run = "mattrax"

[lints]
workspace = true

[package.metadata.lambda.deploy]
memory = 512
timeout = 60
arm64 = true
env_file = ".env.production"
tags = { "repo" = "mattrax/Mattrax" }
enable_function_url = true

[dependencies]
mx-api = { path = "../../crates/mx-api" }
mx-core = { path = "../../crates/mx-core" }
axum.workspace = true
clap = { version = "4.5.23", features = ["derive", "env"] }
tokio.workspace = true
tracing.workspace = true
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
lambda_http = "0.14.0"
