[package]
name = "mattrax"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.9"
clap = { version = "4.5.23", features = ["derive"] }
mx-api = { version = "0.0.0", path = "../../crates/api" }
mx-core = { version = "0.0.0", path = "../../crates/core" }
tokio.workspace = true
tracing.workspace = true
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
